package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.ApplicationModule;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface AppModule extends ApplicationModule 
{
  String findIdUbi(oracle.jbo.Key k);



  oracle.jbo.Key crearLiniaDetall(oracle.jbo.Key key, String idpuesto, String idart, oracle.jbo.domain.Number cantot);

  oracle.jbo.Key crearDocumentEntrada(String idpuesto, String idart, oracle.jbo.domain.Number cantot);






  String getRetirarMac(String puesto);

  String setRetirarMac(String puesto, String value);

  String getAutoSortides(String puesto);

  String setAutoSortides(String puesto, String value);

  SgaresmatOpManViewRow identificarOperacioMacEnPuesto(String idmac);

  String getEstatPuesto(String puesto);

  String setEstatPuesto(String puesto, String value);

  void quizasRetirarMac(String puesto, String macEnPuesto);

  boolean esPuestoManipulacion(String puesto);

  java.util.Set getUbicsPuestoManipulacion(String puesto);





  String getUbicacionPuesto(String idpuesto, String magatzem);

  oracle.jbo.RowSet macsEnPuesto(String ubics, String estado);


  boolean imprimirPackingList(String iddoc);


  oracle.jbo.domain.Number insertarCabecera(java.sql.ResultSet cabecera);

  boolean insertarDetalle(oracle.jbo.domain.Number iddoc, java.sql.ResultSet detalle);

  boolean insertarBulto(oracle.jbo.domain.Number iddoc, java.sql.ResultSet bulto);


  String actualitzarReferencia(java.sql.ResultSet referencia);

  String eliminarReferencia(java.sql.ResultSet referencia);

  String insertarReferencia(java.sql.ResultSet referencia);

  oracle.jbo.RowIterator llistaBultosPendentsImprimir(String iddoc, String idlin);

  oracle.jbo.RowIterator llistaEntradesPendentsComunicar();

  oracle.jbo.RowIterator llistaSortidesPendentsComunicar();

  oracle.jbo.RowIterator llistaMovimentsPendentsComunicar();

  oracle.jbo.RowIterator llistaStocksPendentsComunicar();

  boolean treureContenidorMagatzem(String idmac, String desti, String puesto);

  int contenidorAmbExistencies(String idmac);

  boolean quizasManipular(String puesto);

  boolean ordreSortidaNova(oracle.jbo.domain.Number iddoc);

  java.util.Vector getDisponibilitat(String idmac, String idart);

  String getCapacitatPulmoPuesto(String puesto, boolean isSlo);

  boolean setCapacitatPulmoPuesto(String puesto, oracle.jbo.domain.Number capacitat, boolean isSlo);

  void setEnviarSortidaHost(String iddoc);

  boolean checkUser(String user, String password);

  void netejarBD();

  boolean hasMoreSortidesAuto(String iddoc);

  boolean ordreAmbReservesManuals(oracle.jbo.domain.Number iddoc);

  void setResmanListImpres(String iddoc);

  boolean hasResmanPendentsImprimir();

  boolean hasRole(String role);

  boolean isUserModPes();

  void regularizarTablaStock(String idArt, oracle.jbo.domain.Number cantot);

  boolean insertarEtiqueta(oracle.jbo.domain.Number iddoc, java.sql.ResultSet etiqueta);

  boolean esPuestoExtraPicking(String puesto);

  SgavubicacionlibreminiloadViewRow getUbiLibre(String rotacion);

  boolean isExport(String iddoc);

  boolean isAdministrador();

  oracle.jbo.RowIterator getLiniesDocActual();

  int getLiniesSortidaObertes(String idPuesto);

  boolean existsMac(String idMac);

  boolean isUserModTransportista();

  boolean assignarReservaManual(oracle.jbo.domain.Number idDoc, oracle.jbo.domain.Number idLin, String idArt, String idMac, oracle.jbo.domain.Number canRes);

  String getSeqExped();

  String createSgaExped(SgacdocViewRow cdocRow);

  boolean checkUsername(String user);

  boolean assignarTrasllatManual(String idArt, String idMac);


}