package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class ProdembalajesViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public ProdembalajesViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Ep_DISPLAYWIDTH", "6"},
    {"Ancho_DISPLAYWIDTH", "6"},
    {"Refformato_DISPLAYWIDTH", "12"},
    {"Alto_DISPLAYWIDTH", "6"},
    {"Largo_DISPLAYWIDTH", "6"},
    {"Idformato_DISPLAYWIDTH", "10"},
    {"Descripcion_DISPLAYWIDTH", "30"}};



}