package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgaarticuloViewRow extends Row 
{
  String getIdart();

  void setIdart(String value);

  String getIdartant();

  void setIdartant(String value);

  String getDescrip();

  void setDescrip(String value);

  oracle.jbo.domain.Number getPesunit();

  void setPesunit(oracle.jbo.domain.Number value);

  String getControlpes();

  void setControlpes(String value);

  es.sysmap.interflex.model.bdc.common.FlexiDate getFecultmov();

  void setFecultmov(es.sysmap.interflex.model.bdc.common.FlexiDate value);

  String getCodean();

  void setCodean(String value);

  oracle.jbo.domain.Number getUniemb();

  void setUniemb(oracle.jbo.domain.Number value);

  String getIdtipmac();

  void setIdtipmac(String value);

  oracle.jbo.domain.Number getUnimac();

  void setUnimac(oracle.jbo.domain.Number value);

  String getRelleno();

  void setRelleno(String value);

  String getMultiref();

  void setMultiref(String value);

  String getRotacion();

  void setRotacion(String value);

  String getPicking1();

  void setPicking1(String value);

  String getIdartif();

  void setIdartif(String value);

  oracle.jbo.domain.Number getTolfifo();

  void setTolfifo(oracle.jbo.domain.Number value);

  es.sysmap.interflex.model.bdc.common.FlexiDate getCreatedon();

  es.sysmap.interflex.model.bdc.common.FlexiDate getModifiedon();
}