package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaarticuloViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaarticuloViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Idartif_LABEL", "Article"},
    {"Tipprep_TOOLTIP", "Tipus de preparació (1 persona | 2 persones)"},
    {"Idartif_TOOLTIP", "Identificador de l'article"},
    {"Tipprep_LABEL", "Tipus preparació"}};






}