package es.sysmap.interflex.model.dmc.common;
import es.sysmap.interflex.etiquetes.EtiquetaPicking;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgabultoViewRow extends Row 
{
  void actualitzarBulto(String estat, String puesto);

  String getIdpuesto();

  String getEstado();

  String getEstadoCabecera();



  void treureDeBultoSortida(oracle.jbo.domain.Number idlin);

  javax.swing.DefaultListModel getLlistaBulto();

  oracle.jbo.domain.Number getIdbulto();

  EtiquetaPicking getDadesEtiqueta();

  void setImprimir(String value);

  void modCantLineaBultoSortida(oracle.jbo.domain.Number idlin, int cantTreta);

  void afegirABultoSortida(oracle.jbo.domain.Number idlin, String idart, oracle.jbo.domain.Number cantot, oracle.jbo.domain.Number pes, boolean absolut);
}