package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgabultoViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgabultoViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Alto_LABEL", "Alçada"},
    {"Estado_LABEL", "Estat"},
    {"Idtipobulto_LABEL", "Tipus Embalum (per quantitat)"},
    {"Descestado_TOOLTIP", "Estat global de l'embalum"},
    {"Pesocont_LABEL", "Pes palet/caixa"},
    {"Estado_TOOLTIP", "Estat global de l'embalum"},
    {"Largo_LABEL", "Llarg"},
    {"Descestado_LABEL", "Estat"},
    {"Ancho_LABEL", "Amplada"}};


















}