package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgalbultoViewRow extends Row 
{
  void reservarEntrada(String idmac, oracle.jbo.domain.Number canres);

  oracle.jbo.domain.Number getCanent();

  oracle.jbo.domain.Number getPeso();

  void setEstado(String value);

  oracle.jbo.domain.Number getIdbulto();

  oracle.jbo.domain.Number getCantot();

  String getEstado();
}