package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaldocEntradesViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaldocEntradesViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Idubi_LABEL", "Id. Ubicació"},
    {"Desctipmac_LABEL", "Tipus Contenidor"},
    {"Especial_LABEL", "Especial"},
    {"Cancon_LABEL", "Quantitat"},
    {"Idmac_LABEL", "Contenidor"},
    {"Pesfin_LABEL", "Pes Final"},
    {"Pesini_LABEL", "Pes Inicial"},
    {"Integra_TOOLTIP", "En cas de sortida de l'existència, s'ha de fer per la quantitat total"},
    {"Idubi_TOOLTIP", "Identificador de la ubicació manual"},
    {"Integra_LABEL", "Integra"},
    {"Descestadobulto_LABEL", "Estat embalum"},
    {"Difpes_LABEL", "Afegit / Pes"},
    {"Especial_TOOLTIP", "Indicar si el material es especial (p.ex: Galvanitzat)"},
    {"Descestado_LABEL", "Estat"},
    {"Difpes_TOOLTIP", "Quantitat afegida segons pes"}};





























































}