package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgamovimientoViewRow extends Row 
{
  oracle.jbo.domain.Number getIdmov();

  void setIdmov(oracle.jbo.domain.Number value);

  oracle.jbo.domain.Number getCantot();

  void setCantot(oracle.jbo.domain.Number value);

  String getIdcabstr();

  void setIdcabstr(String value);

  oracle.jbo.domain.Number getIdcabnum();

  void setIdcabnum(oracle.jbo.domain.Number value);

  oracle.jbo.domain.Number getIdlin();

  void setIdlin(oracle.jbo.domain.Number value);

  oracle.jbo.domain.Number getTipord();

  void setTipord(oracle.jbo.domain.Number value);



  oracle.jbo.domain.Number getObjeto();

  void setObjeto(oracle.jbo.domain.Number value);

  String getTipalbaran();

  void setTipalbaran(String value);

  oracle.jbo.domain.Number getNumalbaran();

  void setNumalbaran(oracle.jbo.domain.Number value);

  String getIdart();

  void setIdart(String value);

  es.sysmap.interflex.model.bdc.common.FlexiDate getCreatedon();

  Row getSgastockView();

  void setEstado(String value);

  String getIdartif();

  oracle.jbo.domain.Number getOperario();


}