package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgamacSenseReservaViewRow extends Row 
{
  String getIdmac();

  boolean verificarPes();

  void actualitzarMac();

  oracle.jbo.domain.Number getCantot();
}