package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgamacViewRow extends Row 
{


  String getIdtipmac();

  String getIdmac();

  boolean reservarEntradaMaterial(String idUbiPuesto, String idart, oracle.jbo.domain.Number canres, int idTraslo);

  boolean reservarSalidaMaterial(String idUbiPuesto, String idart, oracle.jbo.domain.Number canres, int idTraslo);

  void reservarMovimientoEntrada(String idUbides, oracle.jbo.domain.Number posicion, int idTraslo);

  String getDescripUbides();

  String getDescripUbipos();

  void situarEnPuesto(String idPuesto);

  boolean isMiniload();

  void actualizarMovimientoEntrada(String idUbides);

  boolean hasExistencies();


}