package es.sysmap.interflex.model.dmc.common;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgaubicacionMiniLoadViewRow extends SgaubicacionViewRow 
{
  String getIdtipalm();

  void setIdtipalm(String value);

  String getIdubi();

  void setIdubi(String value);

  String getIdtipubi();

  void setIdtipubi(String value);

  String getDescrip();

  void setDescrip(String value);

  oracle.jbo.domain.Number getColumna();

  void setColumna(oracle.jbo.domain.Number value);

  oracle.jbo.domain.Number getNivel();

  void setNivel(oracle.jbo.domain.Number value);

  String getLado();

  void setLado(String value);

  String getRotacion();

  void setRotacion(String value);
}