package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionPlcViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionPlcViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Idtipubi_DISPLAYHINT", "Hide"},
    {"Descrip_TOOLTIP", "Descripció de la ubicació"},
    {"Descrip_LABEL", "Descripció"},
    {"Idtipalm_DISPLAYHINT", "Hide"},
    {"Idubi_DISPLAYHINT", "Hide"}};



}