package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavbultoViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavbultoViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Detalles_LABEL", "Núm. Detalls"},
    {"Idbulto_LABEL", "Id.Embalum"},
    {"Idbulto_TOOLTIP", "Identificador de l'embalum"},
    {"Descestado_LABEL", "Estat Embalum"},
    {"Detalles_TOOLTIP", "Número de detalls de l'embalum"}};














}