package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgaventradasCandidateViewRow extends Row 
{
  oracle.jbo.domain.Number getCandis();

  oracle.jbo.domain.Number getCanpen();

  oracle.jbo.domain.Number getIddoc();

  oracle.jbo.domain.Number getIdlin();

  String getIdmac();

  String getIdtipmac();

  boolean reservarEntrada(int idTraslo);
}