package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgavtrasloEntSalRow extends Row 
{
  String getDescrip();

  String getEstadoproceso();

  String getEstadotraslo();

  String getIdtipalm();

  String getIdtipalm1();

  String getIdtipalm2();

  oracle.jbo.domain.Number getIdtraslo();

  String getIdubiEnt();

  String getIdubiPasillo();

  String getIdubiSal();

  oracle.jbo.domain.Number getPasilloactual();

  oracle.jbo.domain.Number getPasillodestino();

  oracle.jbo.domain.Number getPosplc();

  String getestadoPasillo();

  oracle.jbo.domain.Number getidPasillo();

  void setEstadoproceso(String value);

  void setEstadotraslo(String value);

  void setPasilloactual(oracle.jbo.domain.Number value);

  void setPasillodestino(oracle.jbo.domain.Number value);

  void setestadoPasillo(String value);

  String getIdmac();

  boolean isTrasbordoEntrada();

  boolean isTrasbordoSalida();
}