package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavexistenciaViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavexistenciaViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Ubipos_LABEL", "Ubicació actual"},
    {"EspecialAbbreviation_TOOLTIP", "Especial (P.Ex: Galvanizado)"},
    {"Canres_DISPLAYWIDTH", "14"},
    {"Ubides_LABEL", "Ubicació destí"},
    {"Idmac_LABEL", "Contenidor"},
    {"Descarticulo_LABEL", "Descripcio"},
    {"Descvisualdes_LABEL", "Descrip. Destí"},
    {"Descvisualpos_LABEL", "Descip. Posició"},
    {"Createdon_LABEL", "Creada"},
    {"Cantot_DISPLAYWIDTH", "14"},
    {"EspecialAbbreviation_LABEL", "Especial"},
    {"Idart_TOOLTIP", "Identificador de l'article de l'existència"},
    {"Idartif_LABEL", "Article"},
    {"Desctipmac_LABEL", "Tipus Contenidor"},
    {"Idartif_TOOLTIP", "Identificador de l'article de l'existència"},
    {"Posubipos_LABEL", "Posició actual"},
    {"Refformato_LABEL", "Formato"},
    {"Canres_LABEL", "Quant. Reserv."},
    {"Descestexist_LABEL", "Estat"},
    {"Idart_LABEL", "Article"},
    {"Cantot_LABEL", "Quant. Total"},
    {"Posubides_LABEL", "Posició destí"},
    {"Modifiedon_LABEL", "Modificada"},
    {"Multiref_LABEL", "Multireferencia"}};





























}