package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavtrasloEntSalRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavtrasloEntSalRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"DescripvisualEntrada_DISPLAYWIDTH", "20"},
    {"Estadopasillotxt_TOOLTIP", "Estat actual del pasadis del traslo"},
    {"Estadoprocesotraslotxt_DISPLAYWIDTH", "20"},
    {"Pasillodestino_TOOLTIP", "El passadis desti del traslo - si es diferent, el traslo acepta ordres per el passadis destí"},
    {"Estadoprocesotraslotxt_TOOLTIP", "Estat del proces del traslo"},
    {"Estadopasillotxt_DISPLAYWIDTH", "20"},
    {"Estadoproceso_TOOLTIP", "Estat actual del proces del traslo"},
    {"Estadotraslotxt_TOOLTIP", "Estat actual del traslo"},
    {"Idtraslo_LABEL", "Id. del traslo"},
    {"Estadotraslotxt_DISPLAYWIDTH", "20"},
    {"DescripvisualSalida_DISPLAYWIDTH", "20"},
    {"Pasillodestino_LABEL", "Passadis Destí"},
    {"Estadoproceso_LABEL", "Estat proces"},
    {"Estadopasillotxt_LABEL", "Estat pasadis"},
    {"DescripvisualEntrada_LABEL", "Entrada"},
    {"Pasilloactual_LABEL", "Passadis Actual"},
    {"Estadoprocesotraslotxt_LABEL", "Estat proces"},
    {"Descrip_TOOLTIP", "Nom del transelevador"},
    {"Descrip_LABEL", "Nom"},
    {"Idtraslo_TOOLTIP", "Identificador del transelevador"},
    {"Estadotraslotxt_LABEL", "Estat traslo"},
    {"DescripvisualSalida_LABEL", "Sortida"}};













}