package es.sysmap.interflex.model.dmc.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface ZTipoenvioViewRow extends Row 
{
  void setId(oracle.jbo.domain.Number value);

  void setIdformato(oracle.jbo.domain.Number value);

  void setTipoenvio(String value);
}