package es.sysmap.interflex.modelrps.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class ZAgenciatipoenvioViewRowImpl extends ViewRowImpl 
{


  public static final int ID = 0;
  public static final int CODTRA = 1;
  public static final int TIPOENVIO = 2;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public ZAgenciatipoenvioViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Id
   */
  public Integer getId()
  {
    return (Integer)getAttributeInternal(ID);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Id
   */
  public void setId(Integer value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Codtra
   */
  public String getCodtra()
  {
    return (String)getAttributeInternal(CODTRA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Codtra
   */
  public void setCodtra(String value)
  {
    setAttributeInternal(CODTRA, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Tipoenvio
   */
  public String getTipoenvio()
  {
    return (String)getAttributeInternal(TIPOENVIO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Tipoenvio
   */
  public void setTipoenvio(String value)
  {
    setAttributeInternal(TIPOENVIO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case CODTRA:
        return getCodtra();
      case TIPOENVIO:
        return getTipoenvio();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}