package es.sysmap.interflex.model.bdc;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaexpedlbultoImpl extends EntityImpl 
{
  public static final int IDEXPED = 0;
  public static final int IDBULTO = 1;
  public static final int IDDOC = 2;
  public static final int IDLIN = 3;
  public static final int CANTOT = 4;
  public static final int CREATEDBY = 5;
  public static final int CREATEDON = 6;
  public static final int MODIFIEDBY = 7;
  public static final int MODIFIEDON = 8;
  public static final int PESO = 9;
  public static final int SGAEXPEDBULTO = 10;
  public static final int SGAEXPEDBULTO1 = 11;
  public static final int SGALDOC = 12;












  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaexpedlbultoImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.Sgaexpedlbulto");
    }
    return mDefinitionObject;
  }



  public String getIdcabnum () 
  {
    return getSgaldoc().getIdcabnum();
  }
  
  public String getIdartif () 
  {
    return getSgaldoc().getIdartif();
  }









  /**
   * 
   *  Gets the attribute value for Idexped, using the alias name Idexped
   */
  public Number getIdexped()
  {
    return (Number)getAttributeInternal(IDEXPED);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idexped
   */
  public void setIdexped(Number value)
  {
    setAttributeInternal(IDEXPED, value);
  }

  /**
   * 
   *  Gets the attribute value for Idbulto, using the alias name Idbulto
   */
  public Number getIdbulto()
  {
    return (Number)getAttributeInternal(IDBULTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idbulto
   */
  public void setIdbulto(Number value)
  {
    setAttributeInternal(IDBULTO, value);
  }

  /**
   * 
   *  Gets the attribute value for Iddoc, using the alias name Iddoc
   */
  public Number getIddoc()
  {
    return (Number)getAttributeInternal(IDDOC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Iddoc
   */
  public void setIddoc(Number value)
  {
    setAttributeInternal(IDDOC, value);
  }

  /**
   * 
   *  Gets the attribute value for Idlin, using the alias name Idlin
   */
  public Number getIdlin()
  {
    return (Number)getAttributeInternal(IDLIN);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idlin
   */
  public void setIdlin(Number value)
  {
    setAttributeInternal(IDLIN, value);
  }

  /**
   * 
   *  Gets the attribute value for Cantot, using the alias name Cantot
   */
  public Number getCantot()
  {
    return (Number)getAttributeInternal(CANTOT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Cantot
   */
  public void setCantot(Number value)
  {
    setAttributeInternal(CANTOT, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDEXPED:
        return getIdexped();
      case IDBULTO:
        return getIdbulto();
      case IDDOC:
        return getIddoc();
      case IDLIN:
        return getIdlin();
      case CANTOT:
        return getCantot();
      case CREATEDBY:
        return getCreatedby();
      case CREATEDON:
        return getCreatedon();
      case MODIFIEDBY:
        return getModifiedby();
      case MODIFIEDON:
        return getModifiedon();
      case PESO:
        return getPeso();
      case SGAEXPEDBULTO:
        return getSgaexpedbulto();
      case SGAEXPEDBULTO1:
        return getSgaexpedbulto1();
      case SGALDOC:
        return getSgaldoc();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDEXPED:
        setIdexped((Number)value);
        return;
      case IDBULTO:
        setIdbulto((Number)value);
        return;
      case IDDOC:
        setIddoc((Number)value);
        return;
      case IDLIN:
        setIdlin((Number)value);
        return;
      case CANTOT:
        setCantot((Number)value);
        return;
      case PESO:
        setPeso((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   *  Gets the associated entity SgaexpedbultoImpl
   */
  public SgaexpedbultoImpl getSgaexpedbulto()
  {
    return (SgaexpedbultoImpl)getAttributeInternal(SGAEXPEDBULTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgaexpedbultoImpl
   */
  public void setSgaexpedbulto(SgaexpedbultoImpl value)
  {
    setAttributeInternal(SGAEXPEDBULTO, value);
  }


  /**
   * 
   *  Gets the attribute value for Createdby, using the alias name Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Gets the attribute value for Createdon, using the alias name Createdon
   */
  public Date getCreatedon()
  {
    return (Date)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedby, using the alias name Modifiedby
   */
  public String getModifiedby()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedon, using the alias name Modifiedon
   */
  public Date getModifiedon()
  {
    return (Date)getAttributeInternal(MODIFIEDON);
  }

  /**
   * 
   *  Gets the attribute value for Peso, using the alias name Peso
   */
  public Number getPeso()
  {
    return (Number)getAttributeInternal(PESO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Peso
   */
  public void setPeso(Number value)
  {
    setAttributeInternal(PESO, value);
  }

  /**
   * 
   *  Gets the associated entity SgaexpedbultoImpl
   */
  public SgaexpedbultoImpl getSgaexpedbulto1()
  {
    return (SgaexpedbultoImpl)getAttributeInternal(SGAEXPEDBULTO1);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgaexpedbultoImpl
   */
  public void setSgaexpedbulto1(SgaexpedbultoImpl value)
  {
    setAttributeInternal(SGAEXPEDBULTO1, value);
  }


  /**
   * 
   *  Gets the associated entity SgaldocImpl
   */
  public SgaldocImpl getSgaldoc()
  {
    return (SgaldocImpl)getAttributeInternal(SGALDOC);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgaldocImpl
   */
  public void setSgaldoc(SgaldocImpl value)
  {
    setAttributeInternal(SGALDOC, value);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idexped, Number idbulto, Number iddoc, Number idlin)
  {
    return new Key(new Object[] {idexped, idbulto, iddoc, idlin});
  }










}