package es.sysmap.interflex.model.bdc;
import es.sysmap.interflex.model.dmc.ProdembalajesreferenciaViewRowImpl;
import java.util.Vector;
import oracle.jbo.ApplicationModule;
import oracle.jbo.JboException;
import oracle.jbo.ViewObject;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import es.sysmap.interflex.model.bdc.common.FlexiDate;
import oracle.jbo.AttributeList;
import oracle.jbo.domain.Timestamp;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaexistenciaImpl extends EntityImpl 
{
  public static final int IDMAC = 0;
  public static final int CANTOT = 1;
  public static final int IDART = 2;
  public static final int CANRES = 3;
  public static final int ESTADO = 4;
  public static final int BLOQUEO = 5;
  public static final int CREATEDBY = 6;
  public static final int MODIFIEDBY = 7;
  public static final int CREATEDON = 8;
  public static final int MODIFIEDON = 9;
  public static final int INTEGRA = 10;
  public static final int IDARTIF = 11;
  public static final int DESCRIP = 12;
  public static final int FECENT = 13;
  public static final int MOTIVOBLOQUEO = 14;
  public static final int IDFORMATO = 15;
  public static final int ESPECIAL = 16;
  public static final int SGAARTICULO = 17;
  public static final int SGAMAC = 18;
  public static final int SGALBULTO = 19;
  public static final int SGARESMAT = 20;
  public static final int SGARESMAT1 = 21;












































































  private static SgaexistenciaDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaexistenciaImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (SgaexistenciaDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.Sgaexistencia");
    }
    return mDefinitionObject;
  }











  public Number getPesunit()
  {
    return getSgaarticulo().getPesunit();
  }
  
  public Number getCantitatSegonsPes(Number pes)
  {
    return getSgaarticulo().getCantitatSegonsPes(pes);
  }








  /**
   * 
   *  Gets the attribute value for Idmac, using the alias name Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for Cantot, using the alias name Cantot
   */
  public Number getCantot()
  {
    return (Number)getAttributeInternal(CANTOT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Cantot
   */
  public void setCantot(Number value)
  {
    setAttributeInternal(CANTOT, value);
  }

  /**
   * 
   *  Gets the attribute value for Idart, using the alias name Idart
   */
  public String getIdart()
  {
    return (String)getAttributeInternal(IDART);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idart
   */
  public void setIdart(String value)
  {
    setAttributeInternal(IDART, value);
  }





  /**
   * 
   *  Gets the attribute value for Canres, using the alias name Canres
   */
  public Number getCanres()
  {
    return (Number)getAttributeInternal(CANRES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Canres
   */
  public void setCanres(Number value)
  {
    setAttributeInternal(CANRES, value);
  }

  /**
   * 
   *  Gets the attribute value for Estado, using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for Bloqueo, using the alias name Bloqueo
   */
  public String getBloqueo()
  {
    return (String)getAttributeInternal(BLOQUEO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Bloqueo
   */
  public void setBloqueo(String value)
  {
    setAttributeInternal(BLOQUEO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        return getIdmac();
      case CANTOT:
        return getCantot();
      case IDART:
        return getIdart();
      case CANRES:
        return getCanres();
      case ESTADO:
        return getEstado();
      case BLOQUEO:
        return getBloqueo();
      case CREATEDBY:
        return getCreatedby();
      case MODIFIEDBY:
        return getModifiedby();
      case CREATEDON:
        return getCreatedon();
      case MODIFIEDON:
        return getModifiedon();
      case INTEGRA:
        return getIntegra();
      case IDARTIF:
        return getIdartif();
      case DESCRIP:
        return getDescrip();
      case FECENT:
        return getFecent();
      case MOTIVOBLOQUEO:
        return getMotivoBloqueo();
      case IDFORMATO:
        return getIdformato();
      case ESPECIAL:
        return getEspecial();
      case SGARESMAT:
        return getSgaresmat();
      case SGARESMAT1:
        return getSgaresmat1();
      case SGAARTICULO:
        return getSgaarticulo();
      case SGAMAC:
        return getSgamac();
      case SGALBULTO:
        return getSgalbulto();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        setIdmac((String)value);
        return;
      case CANTOT:
        setCantot((Number)value);
        return;
      case IDART:
        setIdart((String)value);
        return;
      case CANRES:
        setCanres((Number)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      case BLOQUEO:
        setBloqueo((String)value);
        return;
      case INTEGRA:
        setIntegra((String)value);
        return;
      case IDARTIF:
        setIdartif((String)value);
        return;
      case DESCRIP:
        setDescrip((String)value);
        return;
      case FECENT:
        setFecent((FlexiDate)value);
        return;
      case MOTIVOBLOQUEO:
        setMotivoBloqueo((String)value);
        return;
      case IDFORMATO:
        setIdformato((Number)value);
        return;
      case ESPECIAL:
        setEspecial((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   *  Gets the associated entity SgaarticuloImpl
   */
  public SgaarticuloImpl getSgaarticulo()
  {
    return (SgaarticuloImpl)getAttributeInternal(SGAARTICULO);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgaarticuloImpl
   */
  public void setSgaarticulo(SgaarticuloImpl value)
  {
    setAttributeInternal(SGAARTICULO, value);
  }


  /**
   * 
   *  Gets the associated entity SgamacImpl
   */
  public SgamacImpl getSgamac()
  {
    return (SgamacImpl)getAttributeInternal(SGAMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgamacImpl
   */
  public void setSgamac(SgamacImpl value)
  {
    setAttributeInternal(SGAMAC, value);
  }


  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgaresmat()
  {
    return (RowIterator)getAttributeInternal(SGARESMAT);
  }


  /**
   * 
   *  Gets the attribute value for Createdby, using the alias name Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdby
   */
  public void setCreatedby(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedby, using the alias name Modifiedby
   */
  public String getModifiedby()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedby
   */
  public void setModifiedby(String value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Createdon, using the alias name Createdon
   */
  public FlexiDate getCreatedon()
  {
    return (FlexiDate)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdon
   */
  public void setCreatedon(FlexiDate value)
  {
    setAttributeInternal(CREATEDON, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedon, using the alias name Modifiedon
   */
  public FlexiDate getModifiedon()
  {
    return (FlexiDate)getAttributeInternal(MODIFIEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedon
   */
  public void setModifiedon(FlexiDate value)
  {
    setAttributeInternal(MODIFIEDON, value);
  }


  /**
   * 
   *  Gets the attribute value for Integra, using the alias name Integra
   */
  public String getIntegra()
  {
    return (String)getAttributeInternal(INTEGRA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Integra
   */
  public void setIntegra(String value)
  {
    setAttributeInternal(INTEGRA, value);
    
    
    // TODO - all cases??
    if (value != null && value.equals("S"))
      setFormat();
  }




  /**
   * 
   *  Add attribute defaulting logic in this method.
   */
  protected void create(AttributeList attributeList)
  {
    super.create(attributeList);
    setBloqueo("N");
    setCanres(new Number(0));
    setCantot(new Number(0));
    setEstado("L");
    setIntegra("N");
    setFecent(FlexiDate.currentDate());
    
  }


  /**
   * Registrar una reserva para entrada / salida de material
   * @param canres
   */
  public void reservarEntrada(Number canres)
  {
    setCanres(getCanres().add(canres));
  }

  /**
   * Afegeix la quantitat cantot a l'existencia
   */
  public void afegirMaterial(Sgamovexist movexist)
  {
    // Actualitzem la quantitat inicial i final a mov.exist
    movexist.setCanini(getCantot());
    movexist.setCanfin(getCantot().add(movexist.getCancon()));
    
    setCantot(getCantot().add(movexist.getCancon()));
    setCanres(getCanres().subtract(movexist.getCanres()));
    
    // Xavi, 17/04/05: Afegim l'atribut integra
    setIntegra(movexist.getIntegra());
    
    setEspecial(movexist.getExistenciaEspecial());
    // Si la quantitat que s'ha mogut es 0, no fem res
    // Insertem el registre corresponent a l'històric    
    SgahistexistDefImpl histexist = (SgahistexistDefImpl)SgahistexistImpl.getDefinitionObject();
    histexist.crearHistoric(getDBTransaction(), movexist);
      
    // Si es tracta d'una regularització a l'alça, o d'una entrada sense document, afegim
    // un registre a sgamovimientos
    if (movexist.getTipmov().equals("R") || movexist.getIdtipdoc().equals("EM"))
    {
      Sgamovimiento movimiento = movexist.getMovimiento();
      movimiento.setTipord(movexist.getTipmov().equals("R") ? new Number(30) : new Number(10));
      SgamovimientoDefImpl moviment = (SgamovimientoDefImpl)SgamovimientoImpl.getDefinitionObject();
      moviment.crearMoviment(getDBTransaction(), movimiento);
    }
    
    setFormat();
  }

  /**
   * Asignar el format a la existencia, si en té
   * Una existencia té format si:
   * No es JLA o CUB (Jaula o cubeta)
   * Es íntegra
   * Existeix un registre pel artícle 
   */
  private void setFormat() 
  {
    if (getSgamac().getIdtipmac().equals("JLA") || getSgamac().getIdtipmac().equals("CUB")) 
      return;
    
    setIdformato(getFormat());
    
  }
  /**
   * Buscar el format de la existencia
   */
  private Number getFormat() 
  {
    ApplicationModule root = this.getDBTransaction().getRootApplicationModule();
    ViewObject vo = root.findViewObject("ProdembalajesreferenciaView2");
    getSgaarticulo().getIdartif();
    vo.setWhereClause(null);
    String where = "codart = '" + getSgaarticulo().getIdartif() + "'" + " and cantidad = " + getCantot();
    vo.setWhereClause(where);
    vo.executeQuery();
    if (vo.hasNext()) 
    {
      ProdembalajesreferenciaViewRowImpl row = (ProdembalajesreferenciaViewRowImpl)vo.next();
      return row.getIdformato();
    }
    
    return null;

  }

  /**
   * Treu la quantitat cantot de l'existencia. Si la quantitat final es 0, esborrem
   * l'existència
   */
  public void treureMaterial(Sgamovexist movexist)
  {
    // La quantitat disponible es cantot - (canresTot - canres)
    Number disp = getCantot().subtract(getCanres()).add(movexist.getCanres());
    if (disp.compareTo(movexist.getCancon()) >= 0)
      {
         // Actualitzem la quantitat inicial i final a mov.exist
         movexist.setCanini(getCantot());
         movexist.setCanfin(getCantot().subtract(movexist.getCancon()));
         
         setCantot(getCantot().subtract(movexist.getCancon()));
        // Number movexistCanres = movexist.getCanres();
        // Number thisCantes = getCanres();
         setCanres(getCanres().subtract(movexist.getCanres()));
         quizasBorrarExistencia();
        // Insertem el registre corresponent a l'històric    
        SgahistexistDefImpl histexist = (SgahistexistDefImpl)SgahistexistImpl.getDefinitionObject();
        histexist.crearHistoric(getDBTransaction(), movexist);
  
        // Si es tracta d'una regularització a la baixa , afegim un registre a 
        // sgamovimientos
        if (movexist.getTipmov().equals(SgatipdocImpl.TIPDOCREGULARIZACION))
        {
          Sgamovimiento movimiento = movexist.getMovimiento();
          movimiento.setTipord(new Number(30));
          SgamovimientoDefImpl moviment = (SgamovimientoDefImpl)SgamovimientoImpl.getDefinitionObject();
          moviment.crearMoviment(getDBTransaction(), movimiento);
        }
      }
    else
      throw new JboException(InterflexMessageBundle.class,
                             InterflexMessageBundle.EXISTENCIES_INSUFICIENTS,
                             new Object[] {getIdmac(), getIdart() });

  }
  
  /**
   * Borrar la existencia (previo a borrar el mac)
   */
  public void treureTot()
  {
    Sgamovexist mov = new Sgamovexist();
    mov.setIdart(getIdart());
    mov.setCanini(getCantot());
    mov.setCanfin(new Number(0));
    mov.setCanres(getCanres());
    mov.setCancon(getCantot());
    mov.setTipmov(SgatipdocImpl.TIPDOCREGULARIZACION);
    mov.setIdmac(getIdmac());
    mov.setUbipos(getSgamac().getUbipos());
    mov.setObserv((String)this.getEntityDef().getProperty("ESBORRAR_CONTAINER"));
    treureMaterial(mov);
    
    
  }


  /**
   * Anula un moviment d'entrada
   * @param canres quantitat reservada
   */
   //TODO: Traspassar tota la informació necessaria en una estructura per crear
   // els històrics
  public void anularAfegirMaterial(Number canres)
  {
    setCanres(getCanres().subtract(canres));
    quizasBorrarExistencia();
  }


  /**
   * Anula un moviment de sortida
   * @param canres quantitat reservada
   */
   //TODO: Traspassar tota la informació necessaria en una estructura per crear
   // els històrics
  public void anularTreureMaterial(Number canres)
  {
       setCanres(getCanres().subtract(canres));
  }

  /**
   * Si la existencia te quantitat 0 i no hi ha cap mes reserva, l'esborrem
   **/
   
  public void quizasBorrarExistencia()
  {
    
    if (getCantot().equals(new Number(0)) && getCanres().equals(new Number(0)))
      remove();
  }


  /**
   * 
   *  Gets the attribute value for Idartif, using the alias name Idartif
   */
  public String getIdartif()
  {
    return (String)getAttributeInternal(IDARTIF);
  }

  /**
   * 
   *  Gets the attribute value for Descrip, using the alias name Descrip
   */
  public String getDescrip()
  {
    return (String)getAttributeInternal(DESCRIP);
  }


  /**
   * 
   *  Gets the attribute value for Fecent, using the alias name Fecent
   */
  public FlexiDate getFecent()
  {
    return (FlexiDate)getAttributeInternal(FECENT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Fecent
   */
  public void setFecent(FlexiDate value)
  {
    setAttributeInternal(FECENT, value);
  }


  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgaresmat1()
  {
    return (RowIterator)getAttributeInternal(SGARESMAT1);
  }


  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idartif
   */
  public void setIdartif(String value)
  {
    setAttributeInternal(IDARTIF, value);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Descrip
   */
  public void setDescrip(String value)
  {
    setAttributeInternal(DESCRIP, value);
  }

  /**
   * 
   * @return el peso de la cantidad cancon según el peso unitario o 0 si no está definido
   * @param cancon la cantidad (unidades)
   */
   public Number getPesTeoric(Number cancon)
   {
    try
    {
      
    Number uniemb = getSgaarticulo().getUniemb();
    if (uniemb == null || uniemb.intValue() == 0)
      uniemb = new Number (1);
      
    Number pesUnit = getSgaarticulo().getPesunit();
    if (pesUnit != null)
    {
      float pesResultFloat = (pesUnit.intValue()/uniemb.intValue())*cancon.intValue();
      Number pesResult = new Number(pesResultFloat / 1000);
      return pesResult;
    }
    else
      return (new Number (0));
    }
    catch (Exception e)
    {
      e.printStackTrace();
      return (new Number(0));
    }
   }

  public boolean isControladaPerPes()
  {
    return (getSgaarticulo().getControlpes() != null && getSgaarticulo().getControlpes().equals("S"));
  }
  
  

  /**
   * Retorna un vector amb informació de la disponibilitat de l'existència
   **/
  
  public Vector getDisponibilitat()
  {
    Vector disponibilitat = new Vector();
    // Mirem si l'existència te alguna reserva
    if (getCanres().compareTo(new Number(0)) > 0)
    {
      if (getCantot().compareTo(getCanres()) > 0)
        disponibilitat.addElement(getEntityDef().getProperty("EXISTENCIA_RESERVADA_PARCIALMENT"));
      else
        disponibilitat.addElement(getEntityDef().getProperty("EXISTENCIA_RESERVADA_TOTALMENT"));
    }
    // Michael 02.02.2009 mirar bloqueo
    if (getBloqueo().equals("S"))
    {
      if (getMotivoBloqueo() != null)
        disponibilitat.addElement(getEntityDef().getProperty("EXISTENCIA_BLOQUEJADA") + " : " + getMotivoBloqueo());
      else
        disponibilitat.addElement(getEntityDef().getProperty("EXISTENCIA_BLOQUEJADA"));
      
    }
    
    // Mirem la disponibilitat del mac
    getSgamac().getDisponibilitat(disponibilitat);

    return disponibilitat;
  }


  /**
   * 
   *  Gets the associated entity SgalbultoImpl
   */
  public SgalbultoImpl getSgalbulto()
  {
    return (SgalbultoImpl)getAttributeInternal(SGALBULTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgalbultoImpl
   */
  public void setSgalbulto(SgalbultoImpl value)
  {
    setAttributeInternal(SGALBULTO, value);
  }


  public String getRotacionExistencia()
  {
    String rot = getSgaarticulo().getRotacion();
    if (rot == null || rot.length() == 0)
      return "C";
    else
      return rot;
  }
  
  
  public boolean isUbicacionManual() 
  {
    return getSgamac().isManual();
  }

  /**
   * 
   *  Gets the attribute value for MotivoBloqueo, using the alias name MotivoBloqueo
   */
  public String getMotivoBloqueo()
  {
    return (String)getAttributeInternal(MOTIVOBLOQUEO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for MotivoBloqueo
   */
  public void setMotivoBloqueo(String value)
  {
    setAttributeInternal(MOTIVOBLOQUEO, value);
  }


  /**
   * 
   *  Gets the attribute value for Idformato, using the alias name Idformato
   */
  public Number getIdformato()
  {
    return (Number)getAttributeInternal(IDFORMATO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idformato
   */
  public void setIdformato(Number value)
  {
    setAttributeInternal(IDFORMATO, value);
  }


  /**
   * 
   *  Gets the attribute value for Especial, using the alias name Especial
   */
  public String getEspecial()
  {
    return (String)getAttributeInternal(ESPECIAL);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Especial
   */
  public void setEspecial(String value)
  {
    setAttributeInternal(ESPECIAL, value);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String idmac, String idart)
  {
    return new Key(new Object[] {idmac, idart});
  }






















































}