package es.sysmap.interflex.model.bdc;
import java.sql.ResultSet;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgalbultoDefImpl extends EntityDefImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgalbultoDefImpl()
  {
  }
  
  public boolean insertarLbulto(DBTransaction txn, 
                                   Number iddoc, ResultSet bulto) 
  {
    SgalbultoImpl lbulto = (SgalbultoImpl)super.createInstance(txn, null);
    return lbulto.insertarLbulto(iddoc, bulto);
  }  
  
}