package es.sysmap.interflex.model.bdc;
import oracle.jbo.Key;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgamactaraDefImpl extends EntityDefImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgamactaraDefImpl()
  {
  }
  
  
  public SgamactaraImpl createInstance(DBTransaction txn, 
                                   String idmac,
                                   String idtipmac,
                                   Number tara)
  {
    // La entidad ya crea la clave primaria a partir de una secuencia
    SgamactaraImpl mac = (SgamactaraImpl)super.createInstance(txn, null);
    mac.setIdmac(idmac);
    mac.setIdtipmac(idtipmac);
    mac.setTara(tara);

    return mac;
  }

}