package es.sysmap.interflex.model.bdc;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.EntityDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgamovimientoDefImpl extends EntityDefImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgamovimientoDefImpl()
  {
  }

  public SgamovimientoImpl crearMoviment(DBTransaction txn, 
                                   Sgamovimiento movimiento)
  {
    // La entidad ya crea la clave primaria a partir de una secuencia
    SgamovimientoImpl moviment = (SgamovimientoImpl)super.createInstance(txn, null);
    moviment.afegirMoviment(movimiento);
    return moviment;
  }
  
  
}