package es.sysmap.interflex.model.bdc;
import es.sysmap.xml.XMLTelegrama;
import java.util.Vector;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import es.sysmap.interflex.model.bdc.common.IdubiType;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import es.sysmap.interflex.model.bdc.common.FlexiDate;
import oracle.xml.parser.v2.XMLNode;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgapasilloImpl extends EntityImpl 
{
  public static final int IDPASILLO = 0;
  public static final int IDUBI = 1;
  public static final int IDUBIENTRADA = 2;
  public static final int IDUBISALIDA = 3;
  public static final int ESTADO = 4;
  public static final int CREATEDBY = 5;
  public static final int MODIFIEDBY = 6;
  public static final int CREATEDON = 7;
  public static final int MODIFIEDON = 8;
  public static final int SGAUBICACIONPASILLO = 9;
  public static final int SGAUBICACIONENTRADA = 10;
  public static final int SGAUBICACIONSALIDA = 11;
  public static final int SGATRASLO = 12;
  public static final int SGATRASLO1 = 13;
  public static final int SGAUBICACIONSILO = 14;









































  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgapasilloImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.Sgapasillo");
    }
    return mDefinitionObject;
  }










































  /**
   * 
   *  Gets the attribute value for idPasillo, using the alias name idPasillo
   */
  public Number getidPasillo()
  {
    return (Number)getAttributeInternal(IDPASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for idPasillo
   */
  public void setidPasillo(Number value)
  {
    setAttributeInternal(IDPASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for idUbiEntrada, using the alias name idUbiEntrada
   */
  public IdubiType getidUbiEntrada()
  {
    return (IdubiType)getAttributeInternal(IDUBIENTRADA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for idUbiEntrada
   */
  public void setidUbiEntrada(IdubiType value)
  {
    setAttributeInternal(IDUBIENTRADA, value);
  }

  /**
   * 
   *  Gets the attribute value for idUbiSalida, using the alias name idUbiSalida
   */
  public IdubiType getidUbiSalida()
  {
    return (IdubiType)getAttributeInternal(IDUBISALIDA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for idUbiSalida
   */
  public void setidUbiSalida(IdubiType value)
  {
    setAttributeInternal(IDUBISALIDA, value);
  }

  /**
   * 
   *  Gets the attribute value for estado, using the alias name estado
   */
  public String getestado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for estado
   */
  public void setestado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDPASILLO:
        return getidPasillo();
      case IDUBI:
        return getidUbi();
      case IDUBIENTRADA:
        return getidUbiEntrada();
      case IDUBISALIDA:
        return getidUbiSalida();
      case ESTADO:
        return getestado();
      case CREATEDBY:
        return getCreatedby();
      case MODIFIEDBY:
        return getModifiedby();
      case CREATEDON:
        return getCreatedon();
      case MODIFIEDON:
        return getModifiedon();
      case SGAUBICACIONPASILLO:
        return getSgaubicacionPasillo();
      case SGAUBICACIONENTRADA:
        return getSgaubicacionEntrada();
      case SGAUBICACIONSALIDA:
        return getSgaubicacionSalida();
      case SGATRASLO:
        return getSgatraslo();
      case SGATRASLO1:
        return getSgatraslo1();
      case SGAUBICACIONSILO:
        return getSgaubicacionSilo();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDPASILLO:
        setidPasillo((Number)value);
        return;
      case IDUBI:
        setidUbi((IdubiType)value);
        return;
      case IDUBIENTRADA:
        setidUbiEntrada((IdubiType)value);
        return;
      case IDUBISALIDA:
        setidUbiSalida((IdubiType)value);
        return;
      case ESTADO:
        setestado((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   *  Gets the attribute value for idUbi, using the alias name idUbi
   */
  public IdubiType getidUbi()
  {
    return (IdubiType)getAttributeInternal(IDUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for idUbi
   */
  public void setidUbi(IdubiType value)
  {
    setAttributeInternal(IDUBI, value);
  }







  /**
   * 
   *  Gets the associated entity SgaubicacionImpl
   */
  public SgaubicacionImpl getSgaubicacionEntrada()
  {
    return (SgaubicacionImpl)getAttributeInternal(SGAUBICACIONENTRADA);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgaubicacionImpl
   */
  public void setSgaubicacionEntrada(SgaubicacionImpl value)
  {
    setAttributeInternal(SGAUBICACIONENTRADA, value);
  }

















  /**
   * 
   *  Gets the attribute value for Createdby, using the alias name Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdby
   */
  public void setCreatedby(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedby, using the alias name Modifiedby
   */
  public String getModifiedby()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedby
   */
  public void setModifiedby(String value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Createdon, using the alias name Createdon
   */
  public FlexiDate getCreatedon()
  {
    return (FlexiDate)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdon
   */
  public void setCreatedon(FlexiDate value)
  {
    setAttributeInternal(CREATEDON, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedon, using the alias name Modifiedon
   */
  public FlexiDate getModifiedon()
  {
    return (FlexiDate)getAttributeInternal(MODIFIEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedon
   */
  public void setModifiedon(FlexiDate value)
  {
    setAttributeInternal(MODIFIEDON, value);
  }


  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgaubicacionPasillo()
  {
    return (RowIterator)getAttributeInternal(SGAUBICACIONPASILLO);
  }

  /**
   * 
   *  Gets the associated entity SgaubicacionImpl
   */
  public SgaubicacionImpl getSgaubicacionSalida()
  {
    return (SgaubicacionImpl)getAttributeInternal(SGAUBICACIONSALIDA);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgaubicacionImpl
   */
  public void setSgaubicacionSalida(SgaubicacionImpl value)
  {
    setAttributeInternal(SGAUBICACIONSALIDA, value);
  }




  /**
   * Confeccionar el nodo XML correspondiente a la salida pasillo
   * @return 
   * @param node
   */
  public XMLNode getXMLSalidaPasillo(XMLNode node)
  {
    return getSgaubicacionSalida().getXMLUbicacion(node);
  }
  
  /**
   * Confeccionar el nodo XML correspondiente a la entrada pasillo
   * @return 
   * @param node
   */
  public XMLNode getXMLEntradaPasillo(XMLNode node)
  {
    return getSgaubicacionEntrada().getXMLUbicacion(node);
  }


  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgaubicacionSilo()
  {
    return (RowIterator)getAttributeInternal(SGAUBICACIONSILO);
  }





  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgatraslo1()
  {
    return (RowIterator)getAttributeInternal(SGATRASLO1);
  }


  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgatraslo()
  {
    return (RowIterator)getAttributeInternal(SGATRASLO);
  }



  public void getDisponibilitat(Vector disponibilitat)
  {
    // El passadis ha d'estar en funcionament
    if (!(getestado() != null && getestado().equals("1")))
      disponibilitat.addElement(getEntityDef().getProperty("PASSADIS_ATURAT"));
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idPasillo)
  {
    return new Key(new Object[] {idPasillo});
  }



}