package es.sysmap.interflex.model.bdc;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.xml.parser.v2.XMLNode;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgapulmonManutenciónImpl extends SgaubicacionImpl 
{
  public static final int MAXATTRCONST = EntityDefImpl.getMaxAttrConst("es.sysmap.interflex.model.bdc.Sgaubicacion");
  public static final int CAPPUL = MAXATTRCONST;
  public static final int OCUPUL = MAXATTRCONST + 1;
  public static final int POSPLC = MAXATTRCONST + 2;
  public static final int ESTADO = MAXATTRCONST + 3;
  public static final int IDTIPALM = 3;












  private static CustomEntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgapulmonManutenciónImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (CustomEntityDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.SgapulmonManutención");
    }
    return mDefinitionObject;
  }















  /**
   * 
   *  Gets the attribute value for Cappul, using the alias name Cappul
   */
  public Number getCappul()
  {
    return (Number)getAttributeInternal(CAPPUL);
  }

  /**
   * 
   *  Gets the attribute value for Ocupul, using the alias name Ocupul
   */
  public Number getOcupul()
  {
    return (Number)getAttributeInternal(OCUPUL);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Ocupul
   */
  public void setOcupul(Number value)
  {
    setAttributeInternal(OCUPUL, value);
  }

  /**
   * 
   *  Gets the attribute value for Posplc, using the alias name Posplc
   */
  public Number getPosplc()
  {
    return (Number)getAttributeInternal(POSPLC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Posplc
   */
  public void setPosplc(Number value)
  {
    setAttributeInternal(POSPLC, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    if (index == CAPPUL)
    {
      return getCappul();
    }
    if (index == OCUPUL)
    {
      return getOcupul();
    }
    if (index == POSPLC)
    {
      return getPosplc();
    }
    if (index == IDTIPALM)
    {
      return getIdtipalm();
    }
    if (index == ESTADO)
    {
      return getEstado();
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    if (index == OCUPUL)
    {
      setOcupul((Number)value);
      return;
    }
    if (index == POSPLC)
    {
      setPosplc((Number)value);
      return;
    }
    if (index == IDTIPALM)
    {
      setIdtipalm((String)value);
      return;
    }
    if (index == ESTADO)
    {
      setEstado((String)value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
    return;
  }





  /**
   * 
   *  Gets the attribute value for Idtipalm, using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return (String)getAttributeInternal(IDTIPALM);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idtipalm
   */
  public void setIdtipalm(String value)
  {
    setAttributeInternal(IDTIPALM, value);
  }

  /**
   * 
   *  Gets the attribute value for Estado, using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }



  public String getTipoAlmacen()
  {
    return ("PulmonManutencion");
  }



  public void liberarUbicacion(SgaposicionubicacionImpl posicion)
  {
    // TODO
  }

  public void ocuparUbicacion(SgaposicionubicacionImpl posicion)
  {
    // TODO
  }

  public void reservarUbicacion(SgaposicionubicacionImpl posicion)
  {
    // TODO
  }
  
  public void quitarReservaUbicacion(SgaposicionubicacionImpl posicion)
  {
    // TODO
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String idubi)
  {
    return new Key(new Object[] {idubi});
  }




  /**
   * Confeccionar el nodo XML correspondiente a la ubicación
   * @return 
   * @param node
   */
  public XMLNode getXMLUbicacion(XMLNode node)
  {
  try 
  {
    node.getFirstChild().setNodeValue(getPosplc().toString());
    node.selectSingleNode("lado").getFirstChild().setNodeValue("0");
    node.selectSingleNode("columna").getFirstChild().setNodeValue("0");
    node.selectSingleNode("nivel").getFirstChild().setNodeValue("0");
  } catch (Exception ex) 
  {
    LOG.error("getXMLUbicacion",ex);
  } 
    return node;
  }






}