package es.sysmap.interflex.model.bdc;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import es.sysmap.interflex.model.bdc.common.FlexiDate;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgatipmactipubiImpl extends EntityImpl 
{
  public static final int IDTIPUBI = 0;
  public static final int IDTIPMAC = 1;
  public static final int CREATEDBY = 2;
  public static final int MODIFIEDBY = 3;
  public static final int CREATEDON = 4;
  public static final int MODIFIEDON = 5;
  public static final int SGATIPOMAC = 6;
  public static final int SGATIPOUBICACION = 7;
















  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgatipmactipubiImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.Sgatipmactipubi");
    }
    return mDefinitionObject;
  }

















  /**
   * 
   *  Gets the attribute value for Idtipubi, using the alias name Idtipubi
   */
  public String getIdtipubi()
  {
    return (String)getAttributeInternal(IDTIPUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idtipubi
   */
  public void setIdtipubi(String value)
  {
    setAttributeInternal(IDTIPUBI, value);
  }

  /**
   * 
   *  Gets the attribute value for Idtipmac, using the alias name Idtipmac
   */
  public String getIdtipmac()
  {
    return (String)getAttributeInternal(IDTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idtipmac
   */
  public void setIdtipmac(String value)
  {
    setAttributeInternal(IDTIPMAC, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTIPUBI:
        return getIdtipubi();
      case IDTIPMAC:
        return getIdtipmac();
      case CREATEDBY:
        return getCreatedby();
      case MODIFIEDBY:
        return getModifiedby();
      case CREATEDON:
        return getCreatedon();
      case MODIFIEDON:
        return getModifiedon();
      case SGATIPOMAC:
        return getSgatipomac();
      case SGATIPOUBICACION:
        return getSgatipoubicacion();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTIPUBI:
        setIdtipubi((String)value);
        return;
      case IDTIPMAC:
        setIdtipmac((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   *  Gets the associated entity SgatipomacImpl
   */
  public SgatipomacImpl getSgatipomac()
  {
    return (SgatipomacImpl)getAttributeInternal(SGATIPOMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgatipomacImpl
   */
  public void setSgatipomac(SgatipomacImpl value)
  {
    setAttributeInternal(SGATIPOMAC, value);
  }


  /**
   * 
   *  Gets the associated entity SgatipoubicacionImpl
   */
  public SgatipoubicacionImpl getSgatipoubicacion()
  {
    return (SgatipoubicacionImpl)getAttributeInternal(SGATIPOUBICACION);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgatipoubicacionImpl
   */
  public void setSgatipoubicacion(SgatipoubicacionImpl value)
  {
    setAttributeInternal(SGATIPOUBICACION, value);
  }


  /**
   * 
   *  Gets the attribute value for Createdby, using the alias name Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdby
   */
  public void setCreatedby(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedby, using the alias name Modifiedby
   */
  public String getModifiedby()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedby
   */
  public void setModifiedby(String value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Createdon, using the alias name Createdon
   */
  public FlexiDate getCreatedon()
  {
    return (FlexiDate)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdon
   */
  public void setCreatedon(FlexiDate value)
  {
    setAttributeInternal(CREATEDON, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedon, using the alias name Modifiedon
   */
  public FlexiDate getModifiedon()
  {
    return (FlexiDate)getAttributeInternal(MODIFIEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedon
   */
  public void setModifiedon(FlexiDate value)
  {
    setAttributeInternal(MODIFIEDON, value);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String idtipubi, String idtipmac)
  {
    return new Key(new Object[] {idtipubi, idtipmac});
  }














}