package es.sysmap.interflex.model.bdc;
import java.util.Vector;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionManualImpl extends SgaubicacionImpl 
{
  public static final int MAXATTRCONST = EntityDefImpl.getMaxAttrConst("es.sysmap.interflex.model.bdc.Sgaubicacion");
  public static final int PASILLO = MAXATTRCONST;
  public static final int COLUMNA = MAXATTRCONST + 1;
  public static final int NIVEL = MAXATTRCONST + 2;
  public static final int ESTADO = MAXATTRCONST + 3;









  private static SgaubicacionDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionManualImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (SgaubicacionDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.SgaubicacionManual");
    }
    return mDefinitionObject;
  }










  /**
   * 
   *  Gets the attribute value for Idtipalm, using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return super.getIdtipalm();
  }

  /**
   * 
   *  Gets the attribute value for Pasillo, using the alias name Pasillo
   */
  public Number getPasillo()
  {
    return (Number)getAttributeInternal(PASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Pasillo
   */
  public void setPasillo(Number value)
  {
    setAttributeInternal(PASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for Columna, using the alias name Columna
   */
  public Number getColumna()
  {
    return (Number)getAttributeInternal(COLUMNA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Columna
   */
  public void setColumna(Number value)
  {
    setAttributeInternal(COLUMNA, value);
  }

  /**
   * 
   *  Gets the attribute value for Nivel, using the alias name Nivel
   */
  public Number getNivel()
  {
    return (Number)getAttributeInternal(NIVEL);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Nivel
   */
  public void setNivel(Number value)
  {
    setAttributeInternal(NIVEL, value);
  }

  /**
   * 
   *  Gets the attribute value for Estado, using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    if (index == PASILLO)
    {
      return getPasillo();
    }
    if (index == COLUMNA)
    {
      return getColumna();
    }
    if (index == NIVEL)
    {
      return getNivel();
    }
    if (index == IDTIPALM)
    {
      return getIdtipalm();
    }
    if (index == ESTADO)
    {
      return getEstado();
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    if (index == PASILLO)
    {
      setPasillo((Number)value);
      return;
    }
    if (index == COLUMNA)
    {
      setColumna((Number)value);
      return;
    }
    if (index == NIVEL)
    {
      setNivel((Number)value);
      return;
    }
    if (index == ESTADO)
    {
      setEstado((String)value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
    return;
  }


  

  public String getTipoAlmacen()
  {
    return ("Manual");
  }
  public void liberarUbicacion(SgaposicionubicacionImpl posicion)
  {
    setEstado("L");
  }

  public void ocuparUbicacion(SgaposicionubicacionImpl posicion)
  {
    setEstado("O");
  }

  public void reservarUbicacion(SgaposicionubicacionImpl posicion)
  {
    if (getEstado().equals("L"))
    {
      setEstado("R");
    }
    else
    {
      LOG.error("intent de reservar la ubicació: " + toString() + " amb estat: " + getEstado());
    }

  }
  
  public void quitarReservaUbicacion(SgaposicionubicacionImpl posicion)
  {
    if (getEstado().equals("R"))
      setEstado ("L");
  }



  public String getDescripvisual()
  {
    String magatzem = getEntityDef().getAttributeDefImpl(getAttributeIndexOf("Idtipalm")).getLabel(null)  + ": " +  this.getIdtipalm();
    String passadis = getEntityDef().getAttributeDefImpl(getAttributeIndexOf("Pasillo")).getLabel(null)  + ": " +  this.getPasillo();
    String columna = getEntityDef().getAttributeDefImpl(getAttributeIndexOf("Columna")).getLabel(null) + ": " + this.getColumna();
    String nivell = getEntityDef().getAttributeDefImpl(getAttributeIndexOf("Nivel")).getLabel(null) + ": " + this.getNivel();
    
    return  magatzem + " " + passadis + " " + columna + " " + nivell;
  }


  public void getDisponibilitat(SgaposicionubicacionImpl posicioUbicacio, Vector disponibilitat)
  {
    // La ubicació ha d'estar ocupada
    if (!(getEstado() != null && getEstado().equals("O")))
      disponibilitat.addElement(getEntityDef().getProperty("UBICACIO_LLIURE"));
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String idubi)
  {
    return new Key(new Object[] {idubi});
  }



  

}