package es.sysmap.interflex.model.bdc;
import es.sysmap.interflex.model.bdc.SgaposicionubicacionImpl;
import java.util.Vector;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import es.sysmap.interflex.model.bdc.common.FlexiDate;
import oracle.xml.parser.v2.XMLNode;
import org.apache.log4j.Logger;
import org.w3c.dom.Node;

//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionImpl extends EntityImpl 
{
  public static final int IDUBI = 0;
  public static final int IDTIPUBI = 1;
  public static final int DESCRIP = 2;
  public static final int IDTIPALM = 3;
  public static final int CREATEDBY = 4;
  public static final int MODIFIEDBY = 5;
  public static final int CREATEDON = 6;
  public static final int MODIFIEDON = 7;
  public static final int DESCRIPVISUAL = 8;
  public static final int ZONAMAN = 9;
  public static final int SGATIPOALMACEN = 10;
  public static final int SGATIPOUBICACION = 11;
  public static final int SGAPASILLO = 12;
  public static final int SGAZONAMAN = 13;
  public static final int SGAPOSICIONUBICACION = 14;
  public static final int SGAMACDESTINO = 15;
  public static final int SGAMACPOSICION = 16;


  // Algunos constantes para tratamiento de comunicaciones
  public static final String MINILOAD = "MLD";
  public static final String SILO = "SLO";
  public static final String PK1SLO = "PK1SLO";
  public static final String PK1MLD = "PK1MLD";
  public static final String PKML99 = "PKML99";
  
  public static final int POSPLC_ENTRADA_EXTRA = 45;  // La entrada extra
  public static final int POSPLC_ENTRADA_EXTRA_MESA_PASILLO = 44; // La mesa de entrega al pasillo 1
  public static final int POSPLC_GALIBO_6 = 6;  // Gálibo puestos 1 y 2 maxi load
  public static final int POSPLC_GALIBO_44 = 44;  // Gálibo entrada extra maxi load
  public static final int POSPLC_9 = 9; // Retorno mesas maxi load
  public static final int POSPLC_27 = 27; // Salida pasillo 1
  public static final int POSPLC_32 = 32; // Salida pasillo 2
  public static final int POSPLC_37 = 37; // Salida pasillo 3
  public static final int POSPLC_42 = 42; // Salida Pasillo 4
  public static final int POSPLC_54 = 54; // Picking 1 MLD
  public static final int POSPLC_56 = 56; // Picking 2 MLD
  public static final int POSPLC_58 = 58; // Mesa de recogida miniload
  
  
  
  public static final int PASILLO_1 = 1;

  protected Logger LOG = Logger.getLogger(getClass());



























  private static SgaubicacionDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (SgaubicacionDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.Sgaubicacion");
    }
    return mDefinitionObject;
  }


































  public Number getPosplc()
  {
    LOG.error("getPosplc() en SgaUbicación idubi: " + getIdubi() + " tipalm: " + getIdtipalm());
    return new Number(0);
  }


























  /**
   * 
   *  Gets the attribute value for Idubi, using the alias name Idubi
   */
  public String getIdubi()
  {
    return (String)getAttributeInternal(IDUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idubi
   */
  public void setIdubi(String value)
  {
    setAttributeInternal(IDUBI, value);
  }









  /**
   * 
   *  Gets the attribute value for Idtipubi, using the alias name Idtipubi
   */
  public String getIdtipubi()
  {
    return (String)getAttributeInternal(IDTIPUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idtipubi
   */
  public void setIdtipubi(String value)
  {
    setAttributeInternal(IDTIPUBI, value);
  }



  /**
   * 
   *  Gets the attribute value for Descrip, using the alias name Descrip
   */
  public String getDescrip()
  {
    return (String)getAttributeInternal(DESCRIP);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Descrip
   */
  public void setDescrip(String value)
  {
    setAttributeInternal(DESCRIP, value);
  }









  /**
   * 
   *  Gets the attribute value for Idtipalm, using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return (String)getAttributeInternal(IDTIPALM);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idtipalm
   */
  public void setIdtipalm(String value)
  {
    setAttributeInternal(IDTIPALM, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDUBI:
        return getIdubi();
      case IDTIPUBI:
        return getIdtipubi();
      case DESCRIP:
        return getDescrip();
      case IDTIPALM:
        return getIdtipalm();
      case CREATEDBY:
        return getCreatedby();
      case MODIFIEDBY:
        return getModifiedby();
      case CREATEDON:
        return getCreatedon();
      case MODIFIEDON:
        return getModifiedon();
      case DESCRIPVISUAL:
        return getDescripvisual();
      case ZONAMAN:
        return getZonaman();
      case SGAPOSICIONUBICACION:
        return getSgaposicionubicacion();
      case SGAMACDESTINO:
        return getSgamacDestino();
      case SGAMACPOSICION:
        return getSgamacPosicion();
      case SGATIPOALMACEN:
        return getSgatipoalmacen();
      case SGATIPOUBICACION:
        return getSgatipoubicacion();
      case SGAPASILLO:
        return getSgapasillo();
      case SGAZONAMAN:
        return getSgazonaman();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDUBI:
        setIdubi((String)value);
        return;
      case IDTIPUBI:
        setIdtipubi((String)value);
        return;
      case DESCRIP:
        setDescrip((String)value);
        return;
      case IDTIPALM:
        setIdtipalm((String)value);
        return;
      case DESCRIPVISUAL:
        setDescripvisual((String)value);
        return;
      case ZONAMAN:
        setZonaman((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   *  Gets the associated entity SgatipoalmacenImpl
   */
  public SgatipoalmacenImpl getSgatipoalmacen()
  {
    return (SgatipoalmacenImpl)getAttributeInternal(SGATIPOALMACEN);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgatipoalmacenImpl
   */
  public void setSgatipoalmacen(SgatipoalmacenImpl value)
  {
    setAttributeInternal(SGATIPOALMACEN, value);
  }



  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgaposicionubicacion()
  {
    return (RowIterator)getAttributeInternal(SGAPOSICIONUBICACION);
  }





  /**
   * 
   *  Gets the associated entity SgatipoubicacionImpl
   */
  public SgatipoubicacionImpl getSgatipoubicacion()
  {
    return (SgatipoubicacionImpl)getAttributeInternal(SGATIPOUBICACION);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgatipoubicacionImpl
   */
  public void setSgatipoubicacion(SgatipoubicacionImpl value)
  {
    setAttributeInternal(SGATIPOUBICACION, value);
  }


  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgamacPosicion()
  {
    return (RowIterator)getAttributeInternal(SGAMACPOSICION);
  }


  /**
   * 
   *  Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getSgamacDestino()
  {
    return (RowIterator)getAttributeInternal(SGAMACDESTINO);
  }


  
  public boolean isReservableSalida()
  {
    // TODO Michael - override this
    return true;
  }

  public String getTipoAlmacen()
  {
    return ("Generico");
  }


  /**
   * 
   *  Gets the attribute value for Createdby, using the alias name Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdby
   */
  public void setCreatedby(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedby, using the alias name Modifiedby
   */
  public String getModifiedby()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedby
   */
  public void setModifiedby(String value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for Createdon, using the alias name Createdon
   */
  public FlexiDate getCreatedon()
  {
    return (FlexiDate)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Createdon
   */
  public void setCreatedon(FlexiDate value)
  {
    setAttributeInternal(CREATEDON, value);
  }

  /**
   * 
   *  Gets the attribute value for Modifiedon, using the alias name Modifiedon
   */
  public FlexiDate getModifiedon()
  {
    return (FlexiDate)getAttributeInternal(MODIFIEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Modifiedon
   */
  public void setModifiedon(FlexiDate value)
  {
    setAttributeInternal(MODIFIEDON, value);
  }


  
  public boolean isAlmacenAutomatico()
  {
    if (this instanceof SgaubicacionSiloImpl || this instanceof SgaubicacionMiniLoadImpl)
      return true;
    else
      return false;
  }

  public void liberarUbicacion(SgaposicionubicacionImpl posicion, Number numPos)
  {
    // Implementar en subclasses o no hacer nada
  }

  public void ocuparUbicacion(SgaposicionubicacionImpl posicion, Number numPos)
  { 
    // Implementar en subclasses o no hacer nada
  }

  public void reservarUbicacion(SgaposicionubicacionImpl posicion, Number numPos)
  {
    // Implementar en subclasses o no hacer nada
  }
  
  public void quitarReservaUbicacion(SgaposicionubicacionImpl posicion, Number numPos)
  {
    // Implementar en subclasses o no hacer nada
  }

  public void setPendienteInspeccion(SgaposicionubicacionImpl posicion, Number numPos)
  {
    throw new RuntimeException ("el método no debe ser llamado");
  }
  
  public SgaposicionubicacionImpl getPosicionUbicacionErrorDeposito(String idTipmac, SgaposicionubicacionImpl posicion)
  {
    throw new RuntimeException ("el método no debe ser llamado");
  }
  


  public String toString ()
  {
    return "Cód. Ubi: " + getIdubi() + "(Tip: " + getTipoAlmacen() + ")";
  }




  public XMLNode getXMLUbicacion(XMLNode node)
  {
    // No hay nada que hacer aquí - debe ser extended esto....
    throw new RuntimeException ("el método no debe ser llamado");
  }

  /**
   * 
   *  Gets the attribute value for Descripvisual, using the alias name Descripvisual
   */
  public String getDescripvisual()
  {
    return getDescrip();
//    return (String)getAttributeInternal(DESCRIPVISUAL);
  }


  /**
   * 
   *  Gets the associated entity SgapasilloImpl
   */
  public SgapasilloImpl getSgapasillo()
  {
    return (SgapasilloImpl)getAttributeInternal(SGAPASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgapasilloImpl
   */
  public void setSgapasillo(SgapasilloImpl value)
  {
    setAttributeInternal(SGAPASILLO, value);
  }



  public XMLNode getXMLUbicacionEntrada(XMLNode node)
  {
    throw new RuntimeException ("el método no debe ser llamado");
  }

  public XMLNode getXMLUbicacionSiguiente(XMLNode node, SgaubicacionImpl ubiDes)
  {
    throw new RuntimeException ("el método no debe ser llamado");
  }

  public XMLNode getXMLUbicacionSiguiente(XMLNode node, SgaposicionubicacionImpl posUbiDes)
  {
    throw new RuntimeException ("el método no debe ser llamado");
  }
  
  public boolean is6()
  {
     return (getPosplc().intValue() == POSPLC_GALIBO_6);
  }


  public boolean is6o44()
  {
     return (getPosplc().intValue() == POSPLC_ENTRADA_EXTRA_MESA_PASILLO || getPosplc().intValue() == POSPLC_GALIBO_6);
  }

  public boolean is44()
  {
    return (getPosplc().intValue() == POSPLC_ENTRADA_EXTRA_MESA_PASILLO);
  }

  public boolean is45()
  {
    return (getPosplc().intValue() == POSPLC_ENTRADA_EXTRA);
  }

  public boolean is27()
  {
    return (getPosplc().intValue() == POSPLC_27);
  }
  
  public boolean is58()
  {
    return (getPosplc().intValue() == POSPLC_58);
  }
  
  public boolean isPosPlc(int posPlc)
  {
    if (getPosplc().intValue() == posPlc)
      return true;
    else
      return false;
  }
  

  public boolean isPickingMiniload()
  {
    int posPlc = getPosplc().intValue();
    return (posPlc == POSPLC_54 || posPlc == POSPLC_56);
  }


  /**
   * 
   *  Sets <code>value</code> as the attribute value for Descripvisual
   */
  public void setDescripvisual(String value)
  {
    setAttributeInternal(DESCRIPVISUAL, value);
  }



  public void getDisponibilitat(SgaposicionubicacionImpl posicioUbicacio, Vector disponibilitat)
  {
    
  }

  public boolean alliberarInspeccio(SgaposicionubicacionImpl posicion, Number numPos)
  {
    return false;
  }

  public boolean inspeccionarUbicacio(SgaposicionubicacionImpl posicion, Number numPos, String desti, String idtipmac)
  {
    return false;
  }


  /**
   * 
   *  Gets the attribute value for Zonaman, using the alias name Zonaman
   */
  public String getZonaman()
  {
    return (String)getAttributeInternal(ZONAMAN);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Zonaman
   */
  public void setZonaman(String value)
  {
    setAttributeInternal(ZONAMAN, value);
  }

  /**
   * 
   *  Gets the associated entity SgazonamanImpl
   */
  public SgazonamanImpl getSgazonaman()
  {
    return (SgazonamanImpl)getAttributeInternal(SGAZONAMAN);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity SgazonamanImpl
   */
  public void setSgazonaman(SgazonamanImpl value)
  {
    setAttributeInternal(SGAZONAMAN, value);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String idubi)
  {
    return new Key(new Object[] {idubi});
  }





}