package es.sysmap.interflex.model.bdc;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class ZTipoenvioImpl extends EntityImpl 
{
  public static final int ID = 0;
  public static final int TIPOENVIO = 1;
  public static final int IDFORMATO = 2;



  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public ZTipoenvioImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.model.bdc.ZTipoenvio");
    }
    return mDefinitionObject;
  }




  /**
   * 
   *  Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   *  Gets the attribute value for Tipoenvio, using the alias name Tipoenvio
   */
  public String getTipoenvio()
  {
    return (String)getAttributeInternal(TIPOENVIO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Tipoenvio
   */
  public void setTipoenvio(String value)
  {
    setAttributeInternal(TIPOENVIO, value);
  }

  /**
   * 
   *  Gets the attribute value for Idformato, using the alias name Idformato
   */
  public Number getIdformato()
  {
    return (Number)getAttributeInternal(IDFORMATO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idformato
   */
  public void setIdformato(Number value)
  {
    setAttributeInternal(IDFORMATO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case TIPOENVIO:
        return getTipoenvio();
      case IDFORMATO:
        return getIdformato();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case TIPOENVIO:
        setTipoenvio((String)value);
        return;
      case IDFORMATO:
        setIdformato((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }




}