package es.sysmap.interflex.model.bdc.common;
import oracle.jbo.domain.DomainOwnerInterface;
import oracle.jbo.domain.DomainInterface;
import oracle.jbo.JboException;
import java.io.Serializable;
import oracle.jbo.Transaction;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class IdubiType implements DomainInterface, Serializable 
{
  private String mData;

  protected IdubiType()
  {
    mData = "";
  }

  public IdubiType(String val)
  {
    mData = new String(val);
    validate();
  }

  public Object getData()
  {
    return mData;
  }

  /**
   * 
   *  <b>Internal:</b> <em>Applications should not use this method.</em>
   */
  public void setContext(DomainOwnerInterface owner, Transaction trans, Object obj)
  {
  }

  /**
   * 
   *  Implements domain validation logic and throws a JboException on error.
   */
  protected void validate()
  {
    //   ### Implement custom domain validation logic here. ###
  }

  public String toString()
  {
    if (mData != null)
    {
      return mData.toString();
    }
    return "<null>";
  }

  public boolean equals(Object obj)
  {
    if (obj instanceof DomainInterface)
    {
      if (mData != null)
      {
        return mData.equals(((DomainInterface)obj).getData());
      }
      return ((DomainInterface)obj).getData() == null;
    }
    return false;
  }
}