package es.sysmap.interflex.model.bdc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaexistenciaImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaexistenciaImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Cantot_TOOLTIP", "Quantitat actual"},
    {"Idartif_LABEL", "Article"},
    {"Idartif_TOOLTIP", "Article de l'existencia"},
    {"Cantot_LABEL", "Quantitat"},
    {"Descrip_TOOLTIP", "Descripció de l'article"},
    {"Fecent_LABEL", "Data Entrada"},
    {"Descrip_LABEL", "Descripció"},
    {"Fecent_TOOLTIP", "Antiguitat de l'existència"}};
















}