package es.sysmap.interflex.model.bdc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgalbultoImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgalbultoImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Idartif_LABEL", "Article"},
    {"Estado_LABEL", "Estat bulto"},
    {"Idbulto_LABEL", "Id. Embalum"},
    {"Relleno_LABEL", "Reomplir"},
    {"Idartif_TOOLTIP", "Identificador de l'article"},
    {"Idlin_TOOLTIP", "Identificador de la linia de l'ordre"},
    {"Unimac_LABEL", "Unitats per contenidor"},
    {"Canres_LABEL", "Resv. Embalum"},
    {"Descrip_DISPLAYWIDTH", "75"},
    {"Cantot_LABEL", "Total Embalum"},
    {"Descrip_TOOLTIP", "Descripció de l'article"},
    {"Peso_LABEL", "Pes"},
    {"Idtipmac_LABEL", "Tipus Contenidor"},
    {"Canpen_LABEL", "Pendent Embalum"},
    {"Descrip_LABEL", "Descripció"},
    {"Idlin_LABEL", "Id. Línia"}};



























}