package es.sysmap.interflex.model.bdc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaresmatImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaresmatImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Idart_TOOLTIP", "Identificador de l'article"},
    {"Idartif_LABEL", "Id. Article"},
    {"Iddoc_TOOLTIP", "Identificador del document"},
    {"Idbulto_LABEL", "Id. Embalum"},
    {"Idartif_TOOLTIP", "Identificador de l'article"},
    {"Idlin_TOOLTIP", "Número de línia"},
    {"Iddoc_LABEL", "Id. Document"},
    {"Idmac_LABEL", "Id. Contenidor"},
    {"Idmac_DISPLAYWIDTH", "20"},
    {"Idbulto_TOOLTIP", "Identificador de l'embalum"},
    {"Canres_LABEL", "Quantitat Reservada"},
    {"Idart_LABEL", "Id. article"},
    {"Canres_TOOLTIP", "Quantitat reservada"},
    {"Idmac_TOOLTIP", "Identificador del contenidor"},
    {"Descrip_TOOLTIP", "Descripció de l'article"},
    {"Descrip_LABEL", "Descripció"},
    {"Idbultopk_DISPLAYHINT", "Hide"},
    {"Idlin_LABEL", "Detall"}};





















}