package es.sysmap.interflex.model.bdc.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Idubi_LABEL", "Id. Ubicació"},
    {"Idtipubi_TOOLTIP", "Tipus ubicació"},
    {"Idtipubi_LABEL", "Tipus Ubicació"},
    {"Idubi_TOOLTIP", "Identificador de la ubicació"},
    {"Descrip_TOOLTIP", "Descripció textual de la ubicació"},
    {"Idtipalm_TOOLTIP", "Tipus de magatzem on es troba la ubicació"},
    {"Descrip_LABEL", "Descripció"},
    {"Idtipalm_LABEL", "Tipus Magatzem"}};






















}