package es.sysmap.interflex.model.dmc;
import oracle.jbo.Key;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgacdocSortidesViewImpl extends SgacdocViewImpl implements es.sysmap.interflex.model.dmc.common.SgacdocSortidesView 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgacdocSortidesViewImpl()
  {
  }
  
  public void findAndSetCurrentRowByKey(Key currentRowKey, int rangePosOfCurrentRow)
  {
    super.findAndSetCurrentRowByKey(currentRowKey, rangePosOfCurrentRow);
  }
    
  
  public void refreshQueryKeepingCurrentRow()   
  {   
      Row currentRow = getCurrentRow();    
      Key currentRowKey = currentRow.getKey();    
      int rangePosOfCurrentRow = getRangeIndexOf(currentRow);    
      int rangeStartBeforeQuery = getRangeStart();    
      executeQuery();    
      setRangeStart(rangeStartBeforeQuery);    
      findAndSetCurrentRowByKey(currentRowKey,rangePosOfCurrentRow);
   }

}