package es.sysmap.interflex.erpsproduccion.model.bdc;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.Key;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class Prod_EmbalajesreferenciaImpl extends EntityImpl 
{
  public static final int CODART = 0;
  public static final int IDFORMATO = 1;
  public static final int CANTIDAD = 2;
  public static final int PREDET = 3;
  public static final int UNIDADMEDIDA = 4;

  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public Prod_EmbalajesreferenciaImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.erpsproduccion.model.bdc.Prod_Embalajesreferencia");
    }
    return mDefinitionObject;
  }


  /**
   * 
   *  Gets the attribute value for Codart, using the alias name Codart
   */
  public String getCodart()
  {
    return (String)getAttributeInternal(CODART);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Codart
   */
  public void setCodart(String value)
  {
    setAttributeInternal(CODART, value);
  }

  /**
   * 
   *  Gets the attribute value for Idformato, using the alias name Idformato
   */
  public Integer getIdformato()
  {
    return (Integer)getAttributeInternal(IDFORMATO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Idformato
   */
  public void setIdformato(Integer value)
  {
    setAttributeInternal(IDFORMATO, value);
  }

  /**
   * 
   *  Gets the attribute value for Cantidad, using the alias name Cantidad
   */
  public Integer getCantidad()
  {
    return (Integer)getAttributeInternal(CANTIDAD);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Cantidad
   */
  public void setCantidad(Integer value)
  {
    setAttributeInternal(CANTIDAD, value);
  }

  /**
   * 
   *  Gets the attribute value for Predet, using the alias name Predet
   */
  public Boolean getPredet()
  {
    return (Boolean)getAttributeInternal(PREDET);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Predet
   */
  public void setPredet(Boolean value)
  {
    setAttributeInternal(PREDET, value);
  }

  /**
   * 
   *  Gets the attribute value for Unidadmedida, using the alias name Unidadmedida
   */
  public String getUnidadmedida()
  {
    return (String)getAttributeInternal(UNIDADMEDIDA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Unidadmedida
   */
  public void setUnidadmedida(String value)
  {
    setAttributeInternal(UNIDADMEDIDA, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CODART:
        return getCodart();
      case IDFORMATO:
        return getIdformato();
      case CANTIDAD:
        return getCantidad();
      case PREDET:
        return getPredet();
      case UNIDADMEDIDA:
        return getUnidadmedida();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CODART:
        setCodart((String)value);
        return;
      case IDFORMATO:
        setIdformato((Integer)value);
        return;
      case CANTIDAD:
        setCantidad((Integer)value);
        return;
      case PREDET:
        setPredet((Boolean)value);
        return;
      case UNIDADMEDIDA:
        setUnidadmedida((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String codart, Integer idformato)
  {
    return new Key(new Object[] {codart, idformato});
  }


}