package es.sysmap.interflex.model.dmc;
import es.sysmap.interflex.model.bdc.InterflexMessageBundle;
import es.sysmap.interflex.model.bdc.Sgamovexist;
import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import es.sysmap.interflex.model.bdc.common.FlexiDate;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgamacSenseReservaViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgamacSenseReservaViewRow 
{


  public static final int IDMAC = 0;
  public static final int MULTIREF = 1;
  public static final int IDTIPMAC = 2;
  public static final int ESTADO = 3;
  public static final int UBIPOS = 4;
  public static final int POSUBIPOS = 5;
  public static final int UBIDES = 6;
  public static final int POSUBIDES = 7;
  public static final int CREATEDBY = 8;
  public static final int MODIFIEDBY = 9;
  public static final int CREATEDON = 10;
  public static final int MODIFIEDON = 11;
  public static final int IDARTIF = 12;
  public static final int IDMAC1 = 13;
  public static final int IDART = 14;
  public static final int DESCRIP = 15;
  public static final int CANCON = 16;
  public static final int PESINI = 17;
  public static final int PESFIN = 18;
  public static final int DIFPES = 19;
  public static final int CANTOT = 20;
  public static final int DESCTIPMAC = 21;
  public static final int OBSERV = 22;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgamacSenseReservaViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgamac entity object.
   */
  public es.sysmap.interflex.model.bdc.SgamacImpl getSgamac()
  {
    return (es.sysmap.interflex.model.bdc.SgamacImpl)getEntity(0);
  }

  /**
   * 
   *  Gets Sgaexistencia entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaexistenciaImpl getSgaexistencia()
  {
    return (es.sysmap.interflex.model.bdc.SgaexistenciaImpl)getEntity(1);
  }

  /**
   * 
   *  Gets the attribute value for IDMAC using the alias name Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDMAC using the alias name Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for MULTIREF using the alias name Multiref
   */
  public String getMultiref()
  {
    return (String)getAttributeInternal(MULTIREF);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for MULTIREF using the alias name Multiref
   */
  public void setMultiref(String value)
  {
    setAttributeInternal(MULTIREF, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPMAC using the alias name Idtipmac
   */
  public String getIdtipmac()
  {
    return (String)getAttributeInternal(IDTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPMAC using the alias name Idtipmac
   */
  public void setIdtipmac(String value)
  {
    setAttributeInternal(IDTIPMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADO using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADO using the alias name Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for UBIPOS using the alias name Ubipos
   */
  public String getUbipos()
  {
    return (String)getAttributeInternal(UBIPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for UBIPOS using the alias name Ubipos
   */
  public void setUbipos(String value)
  {
    setAttributeInternal(UBIPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for POSUBIPOS using the alias name Posubipos
   */
  public Number getPosubipos()
  {
    return (Number)getAttributeInternal(POSUBIPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSUBIPOS using the alias name Posubipos
   */
  public void setPosubipos(Number value)
  {
    setAttributeInternal(POSUBIPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for UBIDES using the alias name Ubides
   */
  public String getUbides()
  {
    return (String)getAttributeInternal(UBIDES);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for UBIDES using the alias name Ubides
   */
  public void setUbides(String value)
  {
    setAttributeInternal(UBIDES, value);
  }

  /**
   * 
   *  Gets the attribute value for POSUBIDES using the alias name Posubides
   */
  public Number getPosubides()
  {
    return (Number)getAttributeInternal(POSUBIDES);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSUBIDES using the alias name Posubides
   */
  public void setPosubides(Number value)
  {
    setAttributeInternal(POSUBIDES, value);
  }

  /**
   * 
   *  Gets the attribute value for CREATEDBY using the alias name Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Gets the attribute value for MODIFIEDBY using the alias name Modifiedby
   */
  public String getModifiedby()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Gets the attribute value for CREATEDON using the alias name Createdon
   */
  public FlexiDate getCreatedon()
  {
    return (FlexiDate)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Gets the attribute value for MODIFIEDON using the alias name Modifiedon
   */
  public FlexiDate getModifiedon()
  {
    return (FlexiDate)getAttributeInternal(MODIFIEDON);
  }

  /**
   * 
   *  Gets the attribute value for IDARTIF using the alias name Idartif
   */
  public String getIdartif()
  {
    return (String)getAttributeInternal(IDARTIF);
  }

  /**
   * 
   *  Gets the attribute value for IDMAC using the alias name Idmac1
   */
  public String getIdmac1()
  {
    return (String)getAttributeInternal(IDMAC1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDMAC using the alias name Idmac1
   */
  public void setIdmac1(String value)
  {
    setAttributeInternal(IDMAC1, value);
  }

  /**
   * 
   *  Gets the attribute value for IDART using the alias name Idart
   */
  public String getIdart()
  {
    return (String)getAttributeInternal(IDART);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDART using the alias name Idart
   */
  public void setIdart(String value)
  {
    setAttributeInternal(IDART, value);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIP using the alias name Descrip
   */
  public String getDescrip()
  {
    return (String)getAttributeInternal(DESCRIP);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Cancon
   */
  public Number getCancon()
  {
    return (Number)getAttributeInternal(CANCON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Cancon
   */
  public void setCancon(Number value)
  {
      //No deixem que la quantitat confirmada sigui negativa
      if (value != null && value.compareTo(new Number(0)) >= 0 )
      {
        setAttributeInternal(CANCON, value);
      }
      else
        throw new JboException(InterflexMessageBundle.class,
                               InterflexMessageBundle.QUANTITAT_NEGATIVA,
                               null);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Pesini
   */
  public Number getPesini()
  {
    return (Number)getAttributeInternal(PESINI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Pesini
   */
  public void setPesini(Number value)
  {
    setAttributeInternal(PESINI, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Pesfin
   */
  public Number getPesfin()
  {
    return (Number)getAttributeInternal(PESFIN);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Pesfin
   */
  public void setPesfin(Number value)
  {
    setAttributeInternal(PESFIN, value);
    // Si l'article va per pes, intentem calcular les unitats
    quizasCalcularDifpes();
    
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Difpes
   */
  public Number getDifpes()
  {
    return (Number)getAttributeInternal(DIFPES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Difpes
   */
  public void setDifpes(Number value)
  {
    setAttributeInternal(DIFPES, value);
  }

  /**
   * 
   *  Gets the attribute value for CANTOT using the alias name Cantot
   */
  public Number getCantot()
  {
    return (Number)getAttributeInternal(CANTOT);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for CANTOT using the alias name Cantot
   */
  public void setCantot(Number value)
  {
    setAttributeInternal(CANTOT, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Desctipmac
   */
  public String getDesctipmac()
  {
    return (String)getAttributeInternal(DESCTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Desctipmac
   */
  public void setDesctipmac(String value)
  {
    setAttributeInternal(DESCTIPMAC, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        return getIdmac();
      case MULTIREF:
        return getMultiref();
      case IDTIPMAC:
        return getIdtipmac();
      case ESTADO:
        return getEstado();
      case UBIPOS:
        return getUbipos();
      case POSUBIPOS:
        return getPosubipos();
      case UBIDES:
        return getUbides();
      case POSUBIDES:
        return getPosubides();
      case CREATEDBY:
        return getCreatedby();
      case MODIFIEDBY:
        return getModifiedby();
      case CREATEDON:
        return getCreatedon();
      case MODIFIEDON:
        return getModifiedon();
      case IDARTIF:
        return getIdartif();
      case IDMAC1:
        return getIdmac1();
      case IDART:
        return getIdart();
      case DESCRIP:
        return getDescrip();
      case CANCON:
        return getCancon();
      case PESINI:
        return getPesini();
      case PESFIN:
        return getPesfin();
      case DIFPES:
        return getDifpes();
      case CANTOT:
        return getCantot();
      case DESCTIPMAC:
        return getDesctipmac();
      case OBSERV:
        return getObserv();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        setIdmac((String)value);
        return;
      case MULTIREF:
        setMultiref((String)value);
        return;
      case IDTIPMAC:
        setIdtipmac((String)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      case UBIPOS:
        setUbipos((String)value);
        return;
      case POSUBIPOS:
        setPosubipos((Number)value);
        return;
      case UBIDES:
        setUbides((String)value);
        return;
      case POSUBIDES:
        setPosubides((Number)value);
        return;
      case IDARTIF:
        setIdartif((String)value);
        return;
      case IDMAC1:
        setIdmac1((String)value);
        return;
      case IDART:
        setIdart((String)value);
        return;
      case DESCRIP:
        setDescrip((String)value);
        return;
      case CANCON:
        setCancon((Number)value);
        return;
      case PESINI:
        setPesini((Number)value);
        return;
      case PESFIN:
        setPesfin((Number)value);
        return;
      case DIFPES:
        setDifpes((Number)value);
        return;
      case CANTOT:
        setCantot((Number)value);
        return;
      case DESCTIPMAC:
        setDesctipmac((String)value);
        return;
      case OBSERV:
        setObserv((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
  
  /**
   * Si l'article es controla per pes, actualitzem difpes
   */
  public void quizasCalcularDifpes()
  {
    setDifpes(getSgaexistencia().getSgaarticulo().calcularDifpes(getPesfin().subtract(getPesini())));
  }


  /**
   * Actualitza el contingut del mac
   */

  public void actualitzarMac()
  {
    if (!getCancon().equals(getCantot()))
    {
      // Posem tota la informació a l'estructura que necessitem per crear l'històric
      Sgamovexist movexist = new Sgamovexist();
      movexist.setCancon(getCancon());
      movexist.setCanres(new Number(0));
      movexist.setIdart(getIdart());
      movexist.setIdbulto(null);
      movexist.setIdcabnum(null);
      movexist.setIdcabstr(null);
      movexist.setIddoc(null);
      movexist.setIdlin(null);
      movexist.setIdmac(getIdmac());
      movexist.setIdtipdoc(null);
      movexist.setObserv(getObserv());
      movexist.setPesfin(getPesfin());
      movexist.setPesini(getPesini());
      movexist.setUbipos(getUbipos());
      movexist.setTipmov("R");
      movexist.setNalbaran(null);
      movexist.setTalbaran(null);
      
      // Actualitzem l'existencia, deixant a cancon la quantitat a afegir o treure
      // per poder utilitzar els mateixos procediments que si fos una entrada o una
      // sortida
      if (getCantot().compareTo(getCancon()) < 0)
      {
        setCancon(getCancon().subtract(getCantot()));
        movexist.setCancon(getCancon());
        getSgamac().afegirMaterial(movexist);
      }
      else
      {
        setCancon(getCantot().subtract(getCancon()));
        movexist.setCancon(getCancon());
        getSgamac().treureMaterial(movexist);
      }
    }
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Observ
   */
  public String getObserv()
  {
    return (String)getAttributeInternal(OBSERV);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Observ
   */
  public void setObserv(String value)
  {
    setAttributeInternal(OBSERV, value);
  }


  /**
   * Retorna cert si s'ha de mostrar una advertencia per la diferencia de pes
   * en l'operació
   * @return 
   */
  public boolean verificarPes()
  {
    boolean verificar = false;
    // Cal controlar el pes?
    if (getSgaexistencia().getSgaarticulo().controlarPes())
    {
      if (getDifpes() != null)
      {
        // TODO: Caldra aplicar un marge de tolerancia...
        if (!(getDifpes().compareTo(getCancon()) == 0))
          verificar = true;
      }
      else
        verificar = true;
    }
    return verificar;
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDARTIF using the alias name Idartif
   */
  public void setIdartif(String value)
  {
    setAttributeInternal(IDARTIF, value);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DESCRIP using the alias name Descrip
   */
  public void setDescrip(String value)
  {
    setAttributeInternal(DESCRIP, value);
  }

}