package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgamacEnPuestoViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgamacEnPuestoViewRow 
{


  public static final int IDMAC = 0;
  public static final int UBIPOS = 1;
  public static final int IDTIPMAC = 2;
  public static final int ESTADO = 3;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgamacEnPuestoViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgamac entity object.
   */
  public es.sysmap.interflex.model.bdc.SgamacImpl getSgamac()
  {
    return (es.sysmap.interflex.model.bdc.SgamacImpl)getEntity(0);
  }

  /**
   * 
   *  Gets the attribute value for IDMAC using the alias name Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDMAC using the alias name Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for UBIPOS using the alias name Ubipos
   */
  public String getUbipos()
  {
    return (String)getAttributeInternal(UBIPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for UBIPOS using the alias name Ubipos
   */
  public void setUbipos(String value)
  {
    setAttributeInternal(UBIPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPMAC using the alias name Idtipmac
   */
  public String getIdtipmac()
  {
    return (String)getAttributeInternal(IDTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPMAC using the alias name Idtipmac
   */
  public void setIdtipmac(String value)
  {
    setAttributeInternal(IDTIPMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADO using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADO using the alias name Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        return getIdmac();
      case UBIPOS:
        return getUbipos();
      case IDTIPMAC:
        return getIdtipmac();
      case ESTADO:
        return getEstado();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        setIdmac((String)value);
        return;
      case UBIPOS:
        setUbipos((String)value);
        return;
      case IDTIPMAC:
        setIdtipmac((String)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
  
  /**
   * Retorna el tipus de carga associat a la reserva
   * @return 
   */
  public String getTipocarga()
  {
    if (getIdtipmac().equals("CUB"))
      return "MLD";
    else
      return "SLO";
  }



  /**
   * Posa el mac en estat en puesto (P)
   */
  public void setMacEnPuesto()
  {
    getSgamac().setEnPuesto();
  }



}