package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaposicionubicacionViewRowImpl extends ViewRowImpl 
{


  public static final int POSICION = 0;
  public static final int ESTADO = 1;
  public static final int IDUBI = 2;
  public static final int ACCESO = 3;
  public static final int SGAMACVIEW = 4;
  public static final int SGAMACVIEW1 = 5;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaposicionubicacionViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgaposicionubicacion entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaposicionubicacionImpl getSgaposicionubicacion()
  {
    return (es.sysmap.interflex.model.bdc.SgaposicionubicacionImpl)getEntity(0);
  }

  /**
   * 
   *  Gets the attribute value for POSICION using the alias name Posicion
   */
  public Number getPosicion()
  {
    return (Number)getAttributeInternal(POSICION);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSICION using the alias name Posicion
   */
  public void setPosicion(Number value)
  {
    setAttributeInternal(POSICION, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADO using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADO using the alias name Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi
   */
  public String getIdubi()
  {
    return (String)getAttributeInternal(IDUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi
   */
  public void setIdubi(String value)
  {
    setAttributeInternal(IDUBI, value);
  }

  /**
   * 
   *  Gets the attribute value for ACCESO using the alias name Acceso
   */
  public String getAcceso()
  {
    return (String)getAttributeInternal(ACCESO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ACCESO using the alias name Acceso
   */
  public void setAcceso(String value)
  {
    setAttributeInternal(ACCESO, value);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgamacView
   */
  public oracle.jbo.RowIterator getSgamacView()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAMACVIEW);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgamacView1
   */
  public oracle.jbo.RowIterator getSgamacView1()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAMACVIEW1);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case POSICION:
        return getPosicion();
      case ESTADO:
        return getEstado();
      case IDUBI:
        return getIdubi();
      case ACCESO:
        return getAcceso();
      case SGAMACVIEW:
        return getSgamacView();
      case SGAMACVIEW1:
        return getSgamacView1();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case POSICION:
        setPosicion((Number)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      case IDUBI:
        setIdubi((String)value);
        return;
      case ACCESO:
        setAcceso((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}