package es.sysmap.interflex.model.dmc;
import es.sysmap.interflex.model.dmc.common.SgaRoleNotGrantedViewRow;
import javax.swing.DefaultListModel;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaRoleNotGrantedViewImpl extends ViewObjectImpl implements es.sysmap.interflex.model.dmc.common.SgaRoleNotGrantedView 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaRoleNotGrantedViewImpl()
  {
  }
  
  public DefaultListModel getListModel(String idUser)
  {
    setWhereClauseParam(0, idUser);
    executeQuery();
    reset();
    DefaultListModel listModel = new DefaultListModel();
    while (hasNext())
    {
      SgaRoleNotGrantedViewRow row = (SgaRoleNotGrantedViewRow)next();
      listModel.addElement(row);
    }
    return listModel;
   }

  // Expose to client
  public Object[] getRowFilterValues()
  {
    return super.getRowFilterValues();
  }

}