package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgatrasloViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgatrasloViewRow 
{


  public static final int IDTRASLO = 0;
  public static final int DESCRIP = 1;
  public static final int ESTADOPROCESO = 2;
  public static final int ESTADOTRASLO = 3;
  public static final int PASILLOACTUAL = 4;
  public static final int PASILLODESTINO = 5;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgatrasloViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgatraslo entity object.
   */
  public es.sysmap.interflex.model.bdc.SgatrasloImpl getSgatraslo()
  {
    return (es.sysmap.interflex.model.bdc.SgatrasloImpl)getEntity(0);
  }

  /**
   * 
   *  Gets the attribute value for IDTRASLO using the alias name Idtraslo
   */
  public Number getIdtraslo()
  {
    return (Number)getAttributeInternal(IDTRASLO);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIP using the alias name Descrip
   */
  public String getDescrip()
  {
    return (String)getAttributeInternal(DESCRIP);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DESCRIP using the alias name Descrip
   */
  public void setDescrip(String value)
  {
    setAttributeInternal(DESCRIP, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADOPROCESO using the alias name Estadoproceso
   */
  public String getEstadoproceso()
  {
    return (String)getAttributeInternal(ESTADOPROCESO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADOPROCESO using the alias name Estadoproceso
   */
  public void setEstadoproceso(String value)
  {
    setAttributeInternal(ESTADOPROCESO, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADOTRASLO using the alias name Estadotraslo
   */
  public String getEstadotraslo()
  {
    return (String)getAttributeInternal(ESTADOTRASLO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADOTRASLO using the alias name Estadotraslo
   */
  public void setEstadotraslo(String value)
  {
    setAttributeInternal(ESTADOTRASLO, value);
  }

  /**
   * 
   *  Gets the attribute value for PASILLOACTUAL using the alias name Pasilloactual
   */
  public Number getPasilloactual()
  {
    return (Number)getAttributeInternal(PASILLOACTUAL);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for PASILLOACTUAL using the alias name Pasilloactual
   */
  public void setPasilloactual(Number value)
  {
    setAttributeInternal(PASILLOACTUAL, value);
  }

  /**
   * 
   *  Gets the attribute value for PASILLODESTINO using the alias name Pasillodestino
   */
  public Number getPasillodestino()
  {
    return (Number)getAttributeInternal(PASILLODESTINO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for PASILLODESTINO using the alias name Pasillodestino
   */
  public void setPasillodestino(Number value)
  {
    setAttributeInternal(PASILLODESTINO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTRASLO:
        return getIdtraslo();
      case DESCRIP:
        return getDescrip();
      case ESTADOPROCESO:
        return getEstadoproceso();
      case ESTADOTRASLO:
        return getEstadotraslo();
      case PASILLOACTUAL:
        return getPasilloactual();
      case PASILLODESTINO:
        return getPasillodestino();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DESCRIP:
        setDescrip((String)value);
        return;
      case ESTADOPROCESO:
        setEstadoproceso((String)value);
        return;
      case ESTADOTRASLO:
        setEstadotraslo((String)value);
        return;
      case PASILLOACTUAL:
        setPasilloactual((Number)value);
        return;
      case PASILLODESTINO:
        setPasillodestino((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}