package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgatdnpobViewRowImpl extends ViewRowImpl 
{
  public static final int PLADISTRIBUIDORA = 0;


  public static final int ZONAREPARTO = 1;
  public static final int CODDELEGACION = 2;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgatdnpobViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Pladistribuidora
   */
  public String getPladistribuidora()
  {
    return (String)getAttributeInternal(PLADISTRIBUIDORA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Pladistribuidora
   */
  public void setPladistribuidora(String value)
  {
    setAttributeInternal(PLADISTRIBUIDORA, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Zonareparto
   */
  public String getZonareparto()
  {
    return (String)getAttributeInternal(ZONAREPARTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Zonareparto
   */
  public void setZonareparto(String value)
  {
    setAttributeInternal(ZONAREPARTO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Coddelegacion
   */
  public String getCoddelegacion()
  {
    return (String)getAttributeInternal(CODDELEGACION);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Coddelegacion
   */
  public void setCoddelegacion(String value)
  {
    setAttributeInternal(CODDELEGACION, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PLADISTRIBUIDORA:
        return getPladistribuidora();
      case ZONAREPARTO:
        return getZonareparto();
      case CODDELEGACION:
        return getCoddelegacion();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PLADISTRIBUIDORA:
        setPladistribuidora((String)value);
        return;
      case ZONAREPARTO:
        setZonareparto((String)value);
        return;
      case CODDELEGACION:
        setCoddelegacion((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}