package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgatipobultoParamViewRowImpl extends ViewRowImpl 
{


  public static final int IDTIP = 0;
  public static final int CANLIN = 1;
  public static final int LARGO = 2;
  public static final int ANCHO = 3;
  public static final int ALTO = 4;
  public static final int PESO = 5;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgatipobultoParamViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgatipobulto entity object.
   */
  public es.sysmap.interflex.model.bdc.SgatipobultoImpl getSgatipobulto()
  {
    return (es.sysmap.interflex.model.bdc.SgatipobultoImpl)getEntity(0);
  }

  /**
   * 
   *  Gets the attribute value for IDTIP using the alias name Idtip
   */
  public String getIdtip()
  {
    return (String)getAttributeInternal(IDTIP);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIP using the alias name Idtip
   */
  public void setIdtip(String value)
  {
    setAttributeInternal(IDTIP, value);
  }

  /**
   * 
   *  Gets the attribute value for CANLIN using the alias name Canlin
   */
  public Number getCanlin()
  {
    return (Number)getAttributeInternal(CANLIN);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for CANLIN using the alias name Canlin
   */
  public void setCanlin(Number value)
  {
    setAttributeInternal(CANLIN, value);
  }

  /**
   * 
   *  Gets the attribute value for LARGO using the alias name Largo
   */
  public Number getLargo()
  {
    return (Number)getAttributeInternal(LARGO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for LARGO using the alias name Largo
   */
  public void setLargo(Number value)
  {
    setAttributeInternal(LARGO, value);
  }

  /**
   * 
   *  Gets the attribute value for ANCHO using the alias name Ancho
   */
  public Number getAncho()
  {
    return (Number)getAttributeInternal(ANCHO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ANCHO using the alias name Ancho
   */
  public void setAncho(Number value)
  {
    setAttributeInternal(ANCHO, value);
  }

  /**
   * 
   *  Gets the attribute value for ALTO using the alias name Alto
   */
  public Number getAlto()
  {
    return (Number)getAttributeInternal(ALTO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ALTO using the alias name Alto
   */
  public void setAlto(Number value)
  {
    setAttributeInternal(ALTO, value);
  }

  /**
   * 
   *  Gets the attribute value for PESO using the alias name Peso
   */
  public Number getPeso()
  {
    return (Number)getAttributeInternal(PESO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for PESO using the alias name Peso
   */
  public void setPeso(Number value)
  {
    setAttributeInternal(PESO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTIP:
        return getIdtip();
      case CANLIN:
        return getCanlin();
      case LARGO:
        return getLargo();
      case ANCHO:
        return getAncho();
      case ALTO:
        return getAlto();
      case PESO:
        return getPeso();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTIP:
        setIdtip((String)value);
        return;
      case CANLIN:
        setCanlin((Number)value);
        return;
      case LARGO:
        setLargo((Number)value);
        return;
      case ANCHO:
        setAncho((Number)value);
        return;
      case ALTO:
        setAlto((Number)value);
        return;
      case PESO:
        setPeso((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}