package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionManualViewRowImpl extends SgaubicacionViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgaubicacionManualViewRow 
{
;


;
;
;
;
  public static final int MAXATTRCONST = oracle.jbo.server.ViewDefImpl.getMaxAttrConst("es.sysmap.interflex.model.dmc.SgaubicacionView");;
  public static final int PASILLO = MAXATTRCONST;
  public static final int COLUMNA = MAXATTRCONST + 1;
  public static final int NIVEL = MAXATTRCONST + 2;
  public static final int ESTADO = MAXATTRCONST + 3;
  public static final int ZONAMAN = MAXATTRCONST + 4;
  public static final int SGAZONAMANVIEW = MAXATTRCONST + 5;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionManualViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgaubicacion entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacion()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionManualImpl)getEntity(0);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return super.getIdtipalm();
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm
   */
  public void setIdtipalm(String value)
  {
    super.setIdtipalm(value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi
   */
  public String getIdubi()
  {
    return super.getIdubi();
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi
   */
  public void setIdubi(String value)
  {
    super.setIdubi(value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPUBI using the alias name Idtipubi
   */
  public String getIdtipubi()
  {
    return super.getIdtipubi();
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPUBI using the alias name Idtipubi
   */
  public void setIdtipubi(String value)
  {
    super.setIdtipubi(value);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIP using the alias name Descrip
   */
  public String getDescrip()
  {
    return super.getDescrip();
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DESCRIP using the alias name Descrip
   */
  public void setDescrip(String value)
  {
    super.setDescrip(value);
  }

  /**
   * 
   *  Gets the attribute value for PASILLO using the alias name Pasillo
   */
  public Number getPasillo()
  {
    return (Number)getAttributeInternal(PASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for PASILLO using the alias name Pasillo
   */
  public void setPasillo(Number value)
  {
    setAttributeInternal(PASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for COLUMNA using the alias name Columna
   */
  public Number getColumna()
  {
    return (Number)getAttributeInternal(COLUMNA);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for COLUMNA using the alias name Columna
   */
  public void setColumna(Number value)
  {
    setAttributeInternal(COLUMNA, value);
  }

  /**
   * 
   *  Gets the attribute value for NIVEL using the alias name Nivel
   */
  public Number getNivel()
  {
    return (Number)getAttributeInternal(NIVEL);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for NIVEL using the alias name Nivel
   */
  public void setNivel(Number value)
  {
    setAttributeInternal(NIVEL, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADO using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADO using the alias name Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    if (index == PASILLO)
    {
      return getPasillo();
    }
    if (index == COLUMNA)
    {
      return getColumna();
    }
    if (index == NIVEL)
    {
      return getNivel();
    }
    if (index == ESTADO)
    {
      return getEstado();
    }
    if (index == ZONAMAN)
    {
      return getZonaman();
    }
    if (index == SGAZONAMANVIEW)
    {
      return getSgazonamanView();
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    if (index == PASILLO)
    {
      setPasillo((Number)value);
      return;
    }
    if (index == COLUMNA)
    {
      setColumna((Number)value);
      return;
    }
    if (index == NIVEL)
    {
      setNivel((Number)value);
      return;
    }
    if (index == ESTADO)
    {
      setEstado((String)value);
      return;
    }
    if (index == ZONAMAN)
    {
      setZonaman((String)value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
    return;
  }

  /**
   * 
   *  Gets the attribute value for ZONAMAN using the alias name Zonaman
   */
  public String getZonaman()
  {
    return (String)getAttributeInternal(ZONAMAN);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ZONAMAN using the alias name Zonaman
   */
  public void setZonaman(String value)
  {
    setAttributeInternal(ZONAMAN, value);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgazonamanView
   */
  public oracle.jbo.RowIterator getSgazonamanView()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAZONAMANVIEW);
  }
}