package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgaubicacionViewRow 
{


  public static final int IDUBI = 0;
  public static final int DESCRIP = 1;
  public static final int IDTIPALM = 2;
  public static final int IDTIPUBI = 3;
  public static final int DESCRIPVISUAL = 4;
  public static final int SGAMACVIEW = 5;
  public static final int SGAMACVIEW3 = 6;
  public static final int SGAPOSICIONUBICACIONVIEW = 7;
  public static final int SGAMACVIEW2 = 6;
  public static final int SGAMACVIEW1 = 6;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionViewRowImpl()
  {
  
  }

  /**
   * 
   *  Gets Sgaubicacion entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacion()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionImpl)getEntity(0);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi
   */
  public String getIdubi()
  {
    return (String)getAttributeInternal(IDUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi
   */
  public void setIdubi(String value)
  {
    setAttributeInternal(IDUBI, value);
  }



  /**
   * 
   *  Gets the attribute value for DESCRIP using the alias name Descrip
   */
  public String getDescrip()
  {
    return (String)getAttributeInternal(DESCRIP);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DESCRIP using the alias name Descrip
   */
  public void setDescrip(String value)
  {
    setAttributeInternal(DESCRIP, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return (String)getAttributeInternal(IDTIPALM);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm
   */
  public void setIdtipalm(String value)
  {
    setAttributeInternal(IDTIPALM, value);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgamacView
   */
  public oracle.jbo.RowIterator getSgamacView()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAMACVIEW);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgamacView1
   */
  public oracle.jbo.RowIterator getSgamacView1()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAMACVIEW1);
  }


  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgaposicionubicacionView
   */
  public oracle.jbo.RowIterator getSgaposicionubicacionView()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAPOSICIONUBICACIONVIEW);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDUBI:
        return getIdubi();
      case DESCRIP:
        return getDescrip();
      case IDTIPALM:
        return getIdtipalm();
      case IDTIPUBI:
        return getIdtipubi();
      case DESCRIPVISUAL:
        return getDescripvisual();
      case SGAMACVIEW:
        return getSgamacView();
      case SGAMACVIEW3:
        return getSgamacView3();
      case SGAPOSICIONUBICACIONVIEW:
        return getSgaposicionubicacionView();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDUBI:
        setIdubi((String)value);
        return;
      case DESCRIP:
        setDescrip((String)value);
        return;
      case IDTIPALM:
        setIdtipalm((String)value);
        return;
      case IDTIPUBI:
        setIdtipubi((String)value);
        return;
      case DESCRIPVISUAL:
        setDescripvisual((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the attribute value for IDTIPUBI using the alias name Idtipubi
   */
  public String getIdtipubi()
  {
    return (String)getAttributeInternal(IDTIPUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPUBI using the alias name Idtipubi
   */
  public void setIdtipubi(String value)
  {
    setAttributeInternal(IDTIPUBI, value);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIPVISUAL using the alias name Descripvisual
   */
  public String getDescripvisual()
  {
    return (String)getAttributeInternal(DESCRIPVISUAL);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgamacView2
   */
  public oracle.jbo.RowIterator getSgamacView2()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAMACVIEW2);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgamacView3
   */
  public oracle.jbo.RowIterator getSgamacView3()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAMACVIEW3);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DESCRIPVISUAL using the alias name Descripvisual
   */
  public void setDescripvisual(String value)
  {
    setAttributeInternal(DESCRIPVISUAL, value);
  }
}