package es.sysmap.interflex.model.dmc;
import es.sysmap.interflex.model.dmc.common.SgamacViewRow;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavmacpendpuestomldViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavmacpendpuestomldViewRow 
{


  public static final int IDMAC = 0;
  public static final int ROTACION = 1;
  public static final int SGAMACVIEW = 2;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavmacpendpuestomldViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Rotacion
   */
  public String getRotacion()
  {
    return (String)getAttributeInternal(ROTACION);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Rotacion
   */
  public void setRotacion(String value)
  {
    setAttributeInternal(ROTACION, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        return getIdmac();
      case ROTACION:
        return getRotacion();
      case SGAMACVIEW:
        return getSgamacView();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        setIdmac((String)value);
        return;
      case ROTACION:
        setRotacion((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  
  public void reservarMovimientoEntrada(String idUbides, oracle.jbo.domain.Number posicion)
  {
    SgamacViewRow mac = (SgamacViewRow)getSgamacView();
    mac.reservarMovimientoEntrada(idUbides, posicion, 0);
  }

  /**
   * 
   *  Gets the associated <code>Row</code> using master-detail link SgamacView
   */
  public oracle.jbo.Row getSgamacView()
  {
    return (oracle.jbo.Row)getAttributeInternal(SGAMACVIEW);
  }

}