package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavtrasloEntSalRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavtrasloEntSalRow 
{


  public static final int IDTRASLO = 0;
  public static final int DESCRIP = 1;
  public static final int ESTADOPROCESO = 2;
  public static final int ESTADOTRASLO = 3;
  public static final int PASILLOACTUAL = 4;
  public static final int PASILLODESTINO = 5;
  public static final int IDUBIENT = 6;
  public static final int IDTIPALM = 7;
  public static final int IDUBISAL = 8;
  public static final int IDTIPALM1 = 9;
  public static final int IDUBIPASILLO = 10;
  public static final int IDTIPALM2 = 11;
  public static final int POSPLC = 12;
  public static final int ESTADOPASILLO = 13;
  public static final int IDPASILLO1_1 = 14;
  public static final int ESTADOTRASLOTXT = 15;
  public static final int ESTADOPASILLOTXT = 16;
  public static final int ESTADOPROCESOTRASLOTXT = 17;
  public static final int TRASBORDOENTRADA = 18;
  public static final int IDMAC = 19;
  public static final int DESCRIPVISUALENTRADA = 20;
  public static final int DESCRIPVISUALSALIDA = 21;
  public static final int IDPASILLO1 = 14;
  public static final int IDPASILLO = 14;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavtrasloEntSalRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgatraslo entity object.
   */
  public es.sysmap.interflex.model.bdc.SgatrasloImpl getSgatraslo()
  {
    return (es.sysmap.interflex.model.bdc.SgatrasloImpl)getEntity(0);
  }

  /**
   * 
   *  Gets Sgapasillo entity object.
   */
  public es.sysmap.interflex.model.bdc.SgapasilloImpl getSgapasillo()
  {
    return (es.sysmap.interflex.model.bdc.SgapasilloImpl)getEntity(1);
  }

  /**
   * 
   *  Gets SgaubicacionPlcEntrada entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacionPlcEntrada()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionPlcImpl)getEntity(2);
  }

  /**
   * 
   *  Gets SgaubicacionPlcSalida entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacionPlcSalida()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionPlcImpl)getEntity(3);
  }

  /**
   * 
   *  Gets SgaubicacionPlc entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacionPlc()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionPlcImpl)getEntity(4);
  }

  /**
   * 
   *  Gets the attribute value for IDTRASLO using the alias name Idtraslo
   */
  public Number getIdtraslo()
  {
    return (Number)getAttributeInternal(IDTRASLO);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIP using the alias name Descrip
   */
  public String getDescrip()
  {
    return (String)getAttributeInternal(DESCRIP);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for DESCRIP using the alias name Descrip
   */
  public void setDescrip(String value)
  {
    setAttributeInternal(DESCRIP, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADOPROCESO using the alias name Estadoproceso
   */
  public String getEstadoproceso()
  {
    return (String)getAttributeInternal(ESTADOPROCESO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADOPROCESO using the alias name Estadoproceso
   */
  public void setEstadoproceso(String value)
  {
    setAttributeInternal(ESTADOPROCESO, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADOTRASLO using the alias name Estadotraslo
   */
  public String getEstadotraslo()
  {
    return (String)getAttributeInternal(ESTADOTRASLO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADOTRASLO using the alias name Estadotraslo
   */
  public void setEstadotraslo(String value)
  {
    setAttributeInternal(ESTADOTRASLO, value);
  }

  /**
   * 
   *  Gets the attribute value for PASILLOACTUAL using the alias name Pasilloactual
   */
  public Number getPasilloactual()
  {
    return (Number)getAttributeInternal(PASILLOACTUAL);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for PASILLOACTUAL using the alias name Pasilloactual
   */
  public void setPasilloactual(Number value)
  {
    setAttributeInternal(PASILLOACTUAL, value);
  }

  /**
   * 
   *  Gets the attribute value for PASILLODESTINO using the alias name Pasillodestino
   */
  public Number getPasillodestino()
  {
    return (Number)getAttributeInternal(PASILLODESTINO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for PASILLODESTINO using the alias name Pasillodestino
   */
  public void setPasillodestino(Number value)
  {
    setAttributeInternal(PASILLODESTINO, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name IdubiEnt
   */
  public String getIdubiEnt()
  {
    return (String)getAttributeInternal(IDUBIENT);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name IdubiEnt
   */
  public void setIdubiEnt(String value)
  {
    setAttributeInternal(IDUBIENT, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return (String)getAttributeInternal(IDTIPALM);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm
   */
  public void setIdtipalm(String value)
  {
    setAttributeInternal(IDTIPALM, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name IdubiSal
   */
  public String getIdubiSal()
  {
    return (String)getAttributeInternal(IDUBISAL);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name IdubiSal
   */
  public void setIdubiSal(String value)
  {
    setAttributeInternal(IDUBISAL, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm1
   */
  public String getIdtipalm1()
  {
    return (String)getAttributeInternal(IDTIPALM1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm1
   */
  public void setIdtipalm1(String value)
  {
    setAttributeInternal(IDTIPALM1, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name IdubiPasillo
   */
  public String getIdubiPasillo()
  {
    return (String)getAttributeInternal(IDUBIPASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name IdubiPasillo
   */
  public void setIdubiPasillo(String value)
  {
    setAttributeInternal(IDUBIPASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm2
   */
  public String getIdtipalm2()
  {
    return (String)getAttributeInternal(IDTIPALM2);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm2
   */
  public void setIdtipalm2(String value)
  {
    setAttributeInternal(IDTIPALM2, value);
  }

  /**
   * 
   *  Gets the attribute value for POSPLC using the alias name Posplc
   */
  public Number getPosplc()
  {
    return (Number)getAttributeInternal(POSPLC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSPLC using the alias name Posplc
   */
  public void setPosplc(Number value)
  {
    setAttributeInternal(POSPLC, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADO using the alias name estadoPasillo
   */
  public String getestadoPasillo()
  {
    return (String)getAttributeInternal(ESTADOPASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADO using the alias name estadoPasillo
   */
  public void setestadoPasillo(String value)
  {
    setAttributeInternal(ESTADOPASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for IDPASILLO using the alias name idPasillo
   */
  public Number getidPasillo()
  {
    return (Number)getAttributeInternal(IDPASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDPASILLO using the alias name idPasillo
   */
  public void setidPasillo(Number value)
  {
    setAttributeInternal(IDPASILLO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTRASLO:
        return getIdtraslo();
      case DESCRIP:
        return getDescrip();
      case ESTADOPROCESO:
        return getEstadoproceso();
      case ESTADOTRASLO:
        return getEstadotraslo();
      case PASILLOACTUAL:
        return getPasilloactual();
      case PASILLODESTINO:
        return getPasillodestino();
      case IDUBIENT:
        return getIdubiEnt();
      case IDTIPALM:
        return getIdtipalm();
      case IDUBISAL:
        return getIdubiSal();
      case IDTIPALM1:
        return getIdtipalm1();
      case IDUBIPASILLO:
        return getIdubiPasillo();
      case IDTIPALM2:
        return getIdtipalm2();
      case POSPLC:
        return getPosplc();
      case ESTADOPASILLO:
        return getestadoPasillo();
      case IDPASILLO1_1:
        return getidPasillo1_1();
      case ESTADOTRASLOTXT:
        return getEstadotraslotxt();
      case ESTADOPASILLOTXT:
        return getEstadopasillotxt();
      case ESTADOPROCESOTRASLOTXT:
        return getEstadoprocesotraslotxt();
      case TRASBORDOENTRADA:
        return getTrasbordoentrada();
      case IDMAC:
        return getIdmac();
      case DESCRIPVISUALENTRADA:
        return getDescripvisualEntrada();
      case DESCRIPVISUALSALIDA:
        return getDescripvisualSalida();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DESCRIP:
        setDescrip((String)value);
        return;
      case ESTADOPROCESO:
        setEstadoproceso((String)value);
        return;
      case ESTADOTRASLO:
        setEstadotraslo((String)value);
        return;
      case PASILLOACTUAL:
        setPasilloactual((Number)value);
        return;
      case PASILLODESTINO:
        setPasillodestino((Number)value);
        return;
      case IDUBIENT:
        setIdubiEnt((String)value);
        return;
      case IDTIPALM:
        setIdtipalm((String)value);
        return;
      case IDUBISAL:
        setIdubiSal((String)value);
        return;
      case IDTIPALM1:
        setIdtipalm1((String)value);
        return;
      case IDUBIPASILLO:
        setIdubiPasillo((String)value);
        return;
      case IDTIPALM2:
        setIdtipalm2((String)value);
        return;
      case POSPLC:
        setPosplc((Number)value);
        return;
      case ESTADOPASILLO:
        setestadoPasillo((String)value);
        return;
      case IDPASILLO1_1:
        setidPasillo1_1((Number)value);
        return;
      case ESTADOTRASLOTXT:
        setEstadotraslotxt((String)value);
        return;
      case ESTADOPASILLOTXT:
        setEstadopasillotxt((String)value);
        return;
      case ESTADOPROCESOTRASLOTXT:
        setEstadoprocesotraslotxt((String)value);
        return;
      case TRASBORDOENTRADA:
        setTrasbordoentrada((String)value);
        return;
      case IDMAC:
        setIdmac((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the attribute value for IDPASILLO using the alias name idPasillo1
   */
  public Number getidPasillo1()
  {
    return (Number)getAttributeInternal(IDPASILLO1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDPASILLO using the alias name idPasillo1
   */
  public void setidPasillo1(Number value)
  {
    setAttributeInternal(IDPASILLO1, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estadotraslotxt
   */
  public String getEstadotraslotxt()
  {
    return (String)getAttributeInternal(ESTADOTRASLOTXT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estadotraslotxt
   */
  public void setEstadotraslotxt(String value)
  {
    setAttributeInternal(ESTADOTRASLOTXT, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estadopasillotxt
   */
  public String getEstadopasillotxt()
  {
    return (String)getAttributeInternal(ESTADOPASILLOTXT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estadopasillotxt
   */
  public void setEstadopasillotxt(String value)
  {
    setAttributeInternal(ESTADOPASILLOTXT, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estadoprocesotraslotxt
   */
  public String getEstadoprocesotraslotxt()
  {
    return (String)getAttributeInternal(ESTADOPROCESOTRASLOTXT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estadoprocesotraslotxt
   */
  public void setEstadoprocesotraslotxt(String value)
  {
    setAttributeInternal(ESTADOPROCESOTRASLOTXT, value);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIPVISUAL using the alias name DescripvisualEntrada
   */
  public String getDescripvisualEntrada()
  {
    return (String)getAttributeInternal(DESCRIPVISUALENTRADA);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIPVISUAL using the alias name DescripvisualSalida
   */
  public String getDescripvisualSalida()
  {
    return (String)getAttributeInternal(DESCRIPVISUALSALIDA);
  }

  /**
   * 
   *  Gets the attribute value for TRASBORDOENTRADA using the alias name Trasbordoentrada
   */
  public String getTrasbordoentrada()
  {
    return (String)getAttributeInternal(TRASBORDOENTRADA);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for TRASBORDOENTRADA using the alias name Trasbordoentrada
   */
  public void setTrasbordoentrada(String value)
  {
    setAttributeInternal(TRASBORDOENTRADA, value);
  }



  /**
   * 
   *  Gets the attribute value for IDPASILLO using the alias name idPasillo1_1
   */
  public Number getidPasillo1_1()
  {
    return (Number)getAttributeInternal(IDPASILLO1_1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDPASILLO using the alias name idPasillo1_1
   */
  public void setidPasillo1_1(Number value)
  {
    setAttributeInternal(IDPASILLO1_1, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }
  
  
  public boolean isTrasbordoSalida()
  {
    return getSgatraslo().getTrasbordosalida().equals("S");
  }
  
  public boolean isTrasbordoEntrada()
  {
    return getSgatraslo().getTrasbordoentrada().equals("S");
  }
}