package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import es.sysmap.interflex.model.bdc.common.FlexiDate;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavhistordtranViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavhistordtranViewRow 
{


  public static final int IDORD = 0;
  public static final int IDMAC = 1;
  public static final int IDORDREUBIC = 2;
  public static final int ESTADOFIN = 3;
  public static final int ESTADOFINTXT = 4;
  public static final int CODERROR = 5;
  public static final int CREATEDON = 6;
  public static final int FECASIG = 7;
  public static final int FECFIN = 8;
  public static final int IDTRASLOINI = 9;
  public static final int IDTRASLOFIN = 10;
  public static final int CREATEDBY = 11;
  public static final int UBIORI = 12;
  public static final int POSUBIORI = 13;
  public static final int UBIDESINI = 14;
  public static final int POSUBIDESINI = 15;
  public static final int UBIDESFIN = 16;
  public static final int POSUBIDESFIN = 17;
  public static final int IDUBI = 18;
  public static final int IDUBI1 = 19;
  public static final int IDUBI2 = 20;
  public static final int IDTIPALM = 21;
  public static final int IDTIPALM1 = 22;
  public static final int IDTIPALM2 = 23;
  public static final int IDHISTORD = 24;
  public static final int ESTADO = 25;
  public static final int UBIORITXT = 26;
  public static final int UBIDESTXT = 27;
  public static final int UBIDESFINTXT = 28;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavhistordtranViewRowImpl()
  {
  }

  /**
   * 
   *  Gets Sgahistordtran entity object.
   */
  public es.sysmap.interflex.model.bdc.SgahistordtranImpl getSgahistordtran()
  {
    return (es.sysmap.interflex.model.bdc.SgahistordtranImpl)getEntity(0);
  }

  /**
   * 
   *  Gets SgaubicacionOri entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacionOri()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionImpl)getEntity(1);
  }

  /**
   * 
   *  Gets SgaubicacionDes entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacionDes()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionImpl)getEntity(2);
  }

  /**
   * 
   *  Gets SgaubicacionDesfin entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacionDesfin()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionImpl)getEntity(3);
  }

  /**
   * 
   *  Gets the attribute value for IDORD using the alias name Idord
   */
  public Number getIdord()
  {
    return (Number)getAttributeInternal(IDORD);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDORD using the alias name Idord
   */
  public void setIdord(Number value)
  {
    setAttributeInternal(IDORD, value);
  }

  /**
   * 
   *  Gets the attribute value for IDMAC using the alias name Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDMAC using the alias name Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for IDORDREUBIC using the alias name Idordreubic
   */
  public Number getIdordreubic()
  {
    return (Number)getAttributeInternal(IDORDREUBIC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDORDREUBIC using the alias name Idordreubic
   */
  public void setIdordreubic(Number value)
  {
    setAttributeInternal(IDORDREUBIC, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADOFIN using the alias name Estadofin
   */
  public String getEstadofin()
  {
    return (String)getAttributeInternal(ESTADOFIN);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADOFIN using the alias name Estadofin
   */
  public void setEstadofin(String value)
  {
    setAttributeInternal(ESTADOFIN, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estadofintxt
   */
  public String getEstadofintxt()
  {
    return (String)getAttributeInternal(ESTADOFINTXT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estadofintxt
   */
  public void setEstadofintxt(String value)
  {
    setAttributeInternal(ESTADOFINTXT, value);
  }

  /**
   * 
   *  Gets the attribute value for CODERROR using the alias name Coderror
   */
  public Number getCoderror()
  {
    return (Number)getAttributeInternal(CODERROR);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for CODERROR using the alias name Coderror
   */
  public void setCoderror(Number value)
  {
    setAttributeInternal(CODERROR, value);
  }

  /**
   * 
   *  Gets the attribute value for CREATEDON using the alias name Createdon
   */
  public FlexiDate getCreatedon()
  {
    return (FlexiDate)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Gets the attribute value for FECASIG using the alias name Fecasig
   */
  public FlexiDate getFecasig()
  {
    return (FlexiDate)getAttributeInternal(FECASIG);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for FECASIG using the alias name Fecasig
   */
  public void setFecasig(FlexiDate value)
  {
    setAttributeInternal(FECASIG, value);
  }

  /**
   * 
   *  Gets the attribute value for FECFIN using the alias name Fecfin
   */
  public FlexiDate getFecfin()
  {
    return (FlexiDate)getAttributeInternal(FECFIN);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for FECFIN using the alias name Fecfin
   */
  public void setFecfin(FlexiDate value)
  {
    setAttributeInternal(FECFIN, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTRASLOINI using the alias name Idtrasloini
   */
  public Number getIdtrasloini()
  {
    return (Number)getAttributeInternal(IDTRASLOINI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTRASLOINI using the alias name Idtrasloini
   */
  public void setIdtrasloini(Number value)
  {
    setAttributeInternal(IDTRASLOINI, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTRASLOFIN using the alias name Idtraslofin
   */
  public Number getIdtraslofin()
  {
    return (Number)getAttributeInternal(IDTRASLOFIN);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTRASLOFIN using the alias name Idtraslofin
   */
  public void setIdtraslofin(Number value)
  {
    setAttributeInternal(IDTRASLOFIN, value);
  }

  /**
   * 
   *  Gets the attribute value for CREATEDBY using the alias name Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Gets the attribute value for UBIORI using the alias name Ubiori
   */
  public String getUbiori()
  {
    return (String)getAttributeInternal(UBIORI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for UBIORI using the alias name Ubiori
   */
  public void setUbiori(String value)
  {
    setAttributeInternal(UBIORI, value);
  }

  /**
   * 
   *  Gets the attribute value for POSUBIORI using the alias name Posubiori
   */
  public Number getPosubiori()
  {
    return (Number)getAttributeInternal(POSUBIORI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSUBIORI using the alias name Posubiori
   */
  public void setPosubiori(Number value)
  {
    setAttributeInternal(POSUBIORI, value);
  }

  /**
   * 
   *  Gets the attribute value for UBIDESINI using the alias name Ubidesini
   */
  public String getUbidesini()
  {
    return (String)getAttributeInternal(UBIDESINI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for UBIDESINI using the alias name Ubidesini
   */
  public void setUbidesini(String value)
  {
    setAttributeInternal(UBIDESINI, value);
  }

  /**
   * 
   *  Gets the attribute value for POSUBIDESINI using the alias name Posubidesini
   */
  public Number getPosubidesini()
  {
    return (Number)getAttributeInternal(POSUBIDESINI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSUBIDESINI using the alias name Posubidesini
   */
  public void setPosubidesini(Number value)
  {
    setAttributeInternal(POSUBIDESINI, value);
  }

  /**
   * 
   *  Gets the attribute value for UBIDESFIN using the alias name Ubidesfin
   */
  public String getUbidesfin()
  {
    return (String)getAttributeInternal(UBIDESFIN);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for UBIDESFIN using the alias name Ubidesfin
   */
  public void setUbidesfin(String value)
  {
    setAttributeInternal(UBIDESFIN, value);
  }

  /**
   * 
   *  Gets the attribute value for POSUBIDESFIN using the alias name Posubidesfin
   */
  public Number getPosubidesfin()
  {
    return (Number)getAttributeInternal(POSUBIDESFIN);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSUBIDESFIN using the alias name Posubidesfin
   */
  public void setPosubidesfin(Number value)
  {
    setAttributeInternal(POSUBIDESFIN, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi
   */
  public String getIdubi()
  {
    return (String)getAttributeInternal(IDUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi
   */
  public void setIdubi(String value)
  {
    setAttributeInternal(IDUBI, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi1
   */
  public String getIdubi1()
  {
    return (String)getAttributeInternal(IDUBI1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi1
   */
  public void setIdubi1(String value)
  {
    setAttributeInternal(IDUBI1, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi2
   */
  public String getIdubi2()
  {
    return (String)getAttributeInternal(IDUBI2);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi2
   */
  public void setIdubi2(String value)
  {
    setAttributeInternal(IDUBI2, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return (String)getAttributeInternal(IDTIPALM);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm
   */
  public void setIdtipalm(String value)
  {
    setAttributeInternal(IDTIPALM, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm1
   */
  public String getIdtipalm1()
  {
    return (String)getAttributeInternal(IDTIPALM1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm1
   */
  public void setIdtipalm1(String value)
  {
    setAttributeInternal(IDTIPALM1, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm2
   */
  public String getIdtipalm2()
  {
    return (String)getAttributeInternal(IDTIPALM2);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm2
   */
  public void setIdtipalm2(String value)
  {
    setAttributeInternal(IDTIPALM2, value);
  }

  /**
   * 
   *  Gets the attribute value for IDHISTORD using the alias name Idhistord
   */
  public Number getIdhistord()
  {
    return (Number)getAttributeInternal(IDHISTORD);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDHISTORD using the alias name Idhistord
   */
  public void setIdhistord(Number value)
  {
    setAttributeInternal(IDHISTORD, value);
  }

  /**
   * 
   *  Gets the attribute value for ESTADO using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADO using the alias name Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIPVISUAL using the alias name UbiOriTxt
   */
  public String getUbiOriTxt()
  {
    return (String)getAttributeInternal(UBIORITXT);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIPVISUAL using the alias name UbiDesTxt
   */
  public String getUbiDesTxt()
  {
    return (String)getAttributeInternal(UBIDESTXT);
  }

  /**
   * 
   *  Gets the attribute value for DESCRIPVISUAL using the alias name UbiDesFinTxt
   */
  public String getUbiDesFinTxt()
  {
    return (String)getAttributeInternal(UBIDESFINTXT);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        return getIdord();
      case IDMAC:
        return getIdmac();
      case IDORDREUBIC:
        return getIdordreubic();
      case ESTADOFIN:
        return getEstadofin();
      case ESTADOFINTXT:
        return getEstadofintxt();
      case CODERROR:
        return getCoderror();
      case CREATEDON:
        return getCreatedon();
      case FECASIG:
        return getFecasig();
      case FECFIN:
        return getFecfin();
      case IDTRASLOINI:
        return getIdtrasloini();
      case IDTRASLOFIN:
        return getIdtraslofin();
      case CREATEDBY:
        return getCreatedby();
      case UBIORI:
        return getUbiori();
      case POSUBIORI:
        return getPosubiori();
      case UBIDESINI:
        return getUbidesini();
      case POSUBIDESINI:
        return getPosubidesini();
      case UBIDESFIN:
        return getUbidesfin();
      case POSUBIDESFIN:
        return getPosubidesfin();
      case IDUBI:
        return getIdubi();
      case IDUBI1:
        return getIdubi1();
      case IDUBI2:
        return getIdubi2();
      case IDTIPALM:
        return getIdtipalm();
      case IDTIPALM1:
        return getIdtipalm1();
      case IDTIPALM2:
        return getIdtipalm2();
      case IDHISTORD:
        return getIdhistord();
      case ESTADO:
        return getEstado();
      case UBIORITXT:
        return getUbiOriTxt();
      case UBIDESTXT:
        return getUbiDesTxt();
      case UBIDESFINTXT:
        return getUbiDesFinTxt();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        setIdord((Number)value);
        return;
      case IDMAC:
        setIdmac((String)value);
        return;
      case IDORDREUBIC:
        setIdordreubic((Number)value);
        return;
      case ESTADOFIN:
        setEstadofin((String)value);
        return;
      case ESTADOFINTXT:
        setEstadofintxt((String)value);
        return;
      case CODERROR:
        setCoderror((Number)value);
        return;
      case FECASIG:
        setFecasig((FlexiDate)value);
        return;
      case FECFIN:
        setFecfin((FlexiDate)value);
        return;
      case IDTRASLOINI:
        setIdtrasloini((Number)value);
        return;
      case IDTRASLOFIN:
        setIdtraslofin((Number)value);
        return;
      case UBIORI:
        setUbiori((String)value);
        return;
      case POSUBIORI:
        setPosubiori((Number)value);
        return;
      case UBIDESINI:
        setUbidesini((String)value);
        return;
      case POSUBIDESINI:
        setPosubidesini((Number)value);
        return;
      case UBIDESFIN:
        setUbidesfin((String)value);
        return;
      case POSUBIDESFIN:
        setPosubidesfin((Number)value);
        return;
      case IDUBI:
        setIdubi((String)value);
        return;
      case IDUBI1:
        setIdubi1((String)value);
        return;
      case IDUBI2:
        setIdubi2((String)value);
        return;
      case IDTIPALM:
        setIdtipalm((String)value);
        return;
      case IDTIPALM1:
        setIdtipalm1((String)value);
        return;
      case IDTIPALM2:
        setIdtipalm2((String)value);
        return;
      case IDHISTORD:
        setIdhistord((Number)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
  
}