package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavordtransalidacursoRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavordtransalidacursoRow 
{


  public static final int IDORD = 0;
  public static final int IDTRASLO = 1;
  public static final int POSPLC = 2;
  public static final int IDMAC = 3;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavordtransalidacursoRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idord
   */
  public Number getIdord()
  {
    return (Number)getAttributeInternal(IDORD);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idord
   */
  public void setIdord(Number value)
  {
    setAttributeInternal(IDORD, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtraslo
   */
  public Number getIdtraslo()
  {
    return (Number)getAttributeInternal(IDTRASLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtraslo
   */
  public void setIdtraslo(Number value)
  {
    setAttributeInternal(IDTRASLO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Posplc
   */
  public Number getPosplc()
  {
    return (Number)getAttributeInternal(POSPLC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Posplc
   */
  public void setPosplc(Number value)
  {
    setAttributeInternal(POSPLC, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        return getIdord();
      case IDTRASLO:
        return getIdtraslo();
      case POSPLC:
        return getPosplc();
      case IDMAC:
        return getIdmac();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        setIdord((Number)value);
        return;
      case IDTRASLO:
        setIdtraslo((Number)value);
        return;
      case POSPLC:
        setPosplc((Number)value);
        return;
      case IDMAC:
        setIdmac((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }
}