package es.sysmap.interflex.model.dmc;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavbultoViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavbultoViewRow  
{


  public static final int IDBULTO = 0;
  public static final int PESO = 1;
  public static final int IDDOC = 2;
  public static final int DETALLES = 3;
  public static final int ESTADO = 4;
  public static final int IDPUESTO = 5;
  public static final int DESCESTADO = 6;
  public static final int SGAVLDOCENTRADESVIEW = 7;
  public static final int SGALDOCENTRADESVIEW = 8;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavbultoViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idbulto
   */
  public Number getIdbulto()
  {
    return (Number)getAttributeInternal(IDBULTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idbulto
   */
  public void setIdbulto(Number value)
  {
    setAttributeInternal(IDBULTO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Peso
   */
  public Number getPeso()
  {
    return (Number)getAttributeInternal(PESO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Peso
   */
  public void setPeso(Number value)
  {
    setAttributeInternal(PESO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Iddoc
   */
  public Number getIddoc()
  {
    return (Number)getAttributeInternal(IDDOC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Iddoc
   */
  public void setIddoc(Number value)
  {
    setAttributeInternal(IDDOC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Detalles
   */
  public Number getDetalles()
  {
    return (Number)getAttributeInternal(DETALLES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Detalles
   */
  public void setDetalles(Number value)
  {
    setAttributeInternal(DETALLES, value);
  }


  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDBULTO:
        return getIdbulto();
      case PESO:
        return getPeso();
      case IDDOC:
        return getIddoc();
      case DETALLES:
        return getDetalles();
      case ESTADO:
        return getEstado();
      case IDPUESTO:
        return getIdpuesto();
      case DESCESTADO:
        return getDescestado();
      case SGAVLDOCENTRADESVIEW:
        return getSgavldocEntradesView();
      case SGALDOCENTRADESVIEW:
        return getSgaldocEntradesView();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDBULTO:
        setIdbulto((Number)value);
        return;
      case PESO:
        setPeso((Number)value);
        return;
      case IDDOC:
        setIddoc((Number)value);
        return;
      case DETALLES:
        setDetalles((Number)value);
        return;
      case IDPUESTO:
        setIdpuesto((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
  

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgavldocEntradesView
   */
  public RowIterator getSgavldocEntradesView()
  {
    return (RowIterator)getAttributeInternal(SGAVLDOCENTRADESVIEW);
  }

  /**
   * 
   *  Retorna un estat global pel bulto en funció de l'estat de les linies del 
   *  bulto
   */
  public String getEstado()
  {
    RowIterator ldocs = getSgavldocEntradesView();
    ldocs.reset();

    String estado = "F";
    
    while (ldocs.hasNext() && !estado.equals("N"))
    {
      SgavldocEntradesViewRowImpl ldoc = (SgavldocEntradesViewRowImpl)ldocs.next();
      switch(ldoc.getEstadobulto().charAt(0))
      {
        case 'N':
        case 'P':
        {
          estado = ldoc.getEstadobulto();
          break;
        }
        case 'S':
        {
          if (estado.equals("F"))
            estado = ldoc.getEstadobulto();
          break;
        }
        case 'A':
        case 'F':
      }
    }
    return estado;
/*    String estado = "N";
    while (ldocs.hasNext() && !estado.equals("P"))
    {
      SgavldocEntradesViewRowImpl ldoc = (SgavldocEntradesViewRowImpl)ldocs.next();
      switch(ldoc.getEstadobulto().charAt(0))
      {
        case 'P':
        {
          estado = ldoc.getEstadobulto();
          break;
        }
        case 'S':
        {
          if (estado.equals("N") || estado.equals("A") || estado.equals("F"))
            estado = ldoc.getEstadobulto();
          break;
        }
        case 'A':
        case 'F':
        {
          if (estado.equals("N"))
            estado = ldoc.getEstadobulto();
          break;
        }
      }
    }
    return estado;*/
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idpuesto
   */
  public String getIdpuesto()
  {
    return (String)getAttributeInternal(IDPUESTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idpuesto
   */
  public void setIdpuesto(String value)
  {
    setAttributeInternal(IDPUESTO, value);
  }






  /**
   * 
   *  Gets the attribute value for the calculated attribute Descestado
   */
  public String getDescestado()
  {
    String queryResult = getApplicationModule().getTransaction().
                    dumpQueryResult("select abbreviation from sgarefcodes where " +
                    "domain ='ESTORD' and value='"+
                          getEstado() +"'", "oracle.jbo.server.QueryDumpTab",
                          null);
    int n = queryResult.indexOf("\n")+1;
    return(queryResult.substring(n).trim());
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Descestado
   */
  public void setDescestado(String value)
  {
    setAttributeInternal(DESCESTADO, value);
  }

  /**
   * 
   *  Gets the associated <code>Row</code> using master-detail link SgaldocEntradesView
   */
  public Row getSgaldocEntradesView()
  {
    return (Row)getAttributeInternal(SGALDOCENTRADESVIEW);
  }




  
}