package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavordtranpasillotrasloViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavordtranpasillotrasloViewRow 
{


  public static final int IDORD = 0;
  public static final int IDMAC = 1;
  public static final int POSPLC = 2;
  public static final int IDUBI = 3;
  public static final int IDTIPALM = 4;
  public static final int IDUBI1 = 5;
  public static final int IDTIPALM1 = 6;
  public static final int ESTADO = 7;
  public static final int IDTRASLO = 8;
  public static final int IDTRASLODESTINO = 9;
  public static final int IDORDREUBIC = 10;
  public static final int SEQMLD = 11;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavordtranpasillotrasloViewRowImpl()
  {
  }







  /**
   * 
   *  Gets the attribute value for IDORD using the alias name Idord
   */
  public Number getIdord()
  {
    return (Number)getAttributeInternal(IDORD);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDORD using the alias name Idord
   */
  public void setIdord(Number value)
  {
    setAttributeInternal(IDORD, value);
  }

  /**
   * 
   *  Gets the attribute value for IDMAC using the alias name Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDMAC using the alias name Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }


  /**
   * 
   *  Gets the attribute value for POSPLC using the alias name Posplc
   */
  public Number getPosplc()
  {
    return (Number)getAttributeInternal(POSPLC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for POSPLC using the alias name Posplc
   */
  public void setPosplc(Number value)
  {
    setAttributeInternal(POSPLC, value);
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi
   */
  public String getIdubi()
  {
    return (String)getAttributeInternal(IDUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi
   */
  public void setIdubi(String value)
  {
    setAttributeInternal(IDUBI, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm
   */
  public String getIdtipalm()
  {
    return (String)getAttributeInternal(IDTIPALM);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm
   */
  public void setIdtipalm(String value)
  {
    setAttributeInternal(IDTIPALM, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        return getIdord();
      case IDMAC:
        return getIdmac();
      case POSPLC:
        return getPosplc();
      case IDUBI:
        return getIdubi();
      case IDTIPALM:
        return getIdtipalm();
      case IDUBI1:
        return getIdubi1();
      case IDTIPALM1:
        return getIdtipalm1();
      case ESTADO:
        return getEstado();
      case IDTRASLO:
        return getIdtraslo();
      case IDTRASLODESTINO:
        return getIdtrasloDestino();
      case IDORDREUBIC:
        return getIdordreubic();
      case SEQMLD:
        return getSeqmld();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        setIdord((Number)value);
        return;
      case IDMAC:
        setIdmac((String)value);
        return;
      case POSPLC:
        setPosplc((Number)value);
        return;
      case IDUBI:
        setIdubi((String)value);
        return;
      case IDTIPALM:
        setIdtipalm((String)value);
        return;
      case IDUBI1:
        setIdubi1((String)value);
        return;
      case IDTIPALM1:
        setIdtipalm1((String)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      case IDTRASLO:
        setIdtraslo((Number)value);
        return;
      case IDORDREUBIC:
        setIdordreubic((Number)value);
        return;
      case SEQMLD:
        setSeqmld((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the attribute value for IDUBI using the alias name Idubi1
   */
  public String getIdubi1()
  {
    return (String)getAttributeInternal(IDUBI1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDUBI using the alias name Idubi1
   */
  public void setIdubi1(String value)
  {
    setAttributeInternal(IDUBI1, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTIPALM using the alias name Idtipalm1
   */
  public String getIdtipalm1()
  {
    return (String)getAttributeInternal(IDTIPALM1);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTIPALM using the alias name Idtipalm1
   */
  public void setIdtipalm1(String value)
  {
    setAttributeInternal(IDTIPALM1, value);
  }


  /**
   * 
   *  Gets the attribute value for ESTADO using the alias name Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ESTADO using the alias name Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }
  
  /**
   * Asignar la orden al traslo y actualizar el estado para que se envíe al PLC
   * @param idTraslo el traslo que realizará la orden
   */
  public void asignarOrdenTraslo (int idTraslo)
  {
    setIdtraslo(new Number(idTraslo));
    setEstado ("N");
  }

  /**
   * 
   *  Gets the attribute value for IDTRASLO using the alias name Idtraslo
   */
  public Number getIdtraslo()
  {
    return (Number)getAttributeInternal(IDTRASLO);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDTRASLO using the alias name Idtraslo
   */
  public void setIdtraslo(Number value)
  {
    setAttributeInternal(IDTRASLO, value);
  }

  /**
   * 
   *  Gets the attribute value for IDTRASLO using the alias name IdtrasloDestino
   */
  public Number getIdtrasloDestino()
  {
    return (Number)getAttributeInternal(IDTRASLODESTINO);
  }

  /**
   * 
   *  Gets Sgaordtran entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaordtranImpl getSgaordtran()
  {
    return (es.sysmap.interflex.model.bdc.SgaordtranImpl)getEntity(0);
  }

  /**
   * 
   *  Gets Sgamac entity object.
   */
  public es.sysmap.interflex.model.bdc.SgamacImpl getSgamac()
  {
    return (es.sysmap.interflex.model.bdc.SgamacImpl)getEntity(1);
  }

  /**
   * 
   *  Gets Sgaubicacion entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacion()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionImpl)getEntity(2);
  }

  /**
   * 
   *  Gets SgaubicacionPlc entity object.
   */
  public es.sysmap.interflex.model.bdc.SgaubicacionImpl getSgaubicacionPlc()
  {
    return (es.sysmap.interflex.model.bdc.SgaubicacionPlcImpl)getEntity(3);
  }

  /**
   * 
   *  Gets Sgatraslo entity object.
   */
  public es.sysmap.interflex.model.bdc.SgatrasloImpl getSgatraslo()
  {
    return (es.sysmap.interflex.model.bdc.SgatrasloImpl)getEntity(4);
  }

  /**
   * 
   *  Gets Sgapasillo entity object.
   */
  public es.sysmap.interflex.model.bdc.SgapasilloImpl getSgapasillo()
  {
    return (es.sysmap.interflex.model.bdc.SgapasilloImpl)getEntity(5);
  }

  /**
   * 
   *  Gets the attribute value for IDORDREUBIC using the alias name Idordreubic
   */
  public Number getIdordreubic()
  {
    return (Number)getAttributeInternal(IDORDREUBIC);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for IDORDREUBIC using the alias name Idordreubic
   */
  public void setIdordreubic(Number value)
  {
    setAttributeInternal(IDORDREUBIC, value);
  }


  public boolean isOrdenReubicacion()
  {
    return getIdordreubic() != null;
  }

  /**
   * 
   *  Gets the attribute value for SEQMLD using the alias name Seqmld
   */
  public Number getSeqmld()
  {
    return (Number)getAttributeInternal(SEQMLD);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for SEQMLD using the alias name Seqmld
   */
  public void setSeqmld(Number value)
  {
    setAttributeInternal(SEQMLD, value);
  }




}