package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavubicacionlibresloViewRowImpl extends ViewRowImpl  
{


  public static final int IDTIPMAC = 0;
  public static final int IDUBI = 1;
  public static final int POSICION = 2;
  public static final int UDISTANCIA = 3;
  public static final int IDTIPUBI = 4;
  public static final int PASILLO = 5;
  public static final int COLUMNA = 6;
  public static final int NIVEL = 7;
  public static final int LADO = 8;
  public static final int ROTACION = 9;
  public static final int NUMPOS = 10;
  public static final int PRIORIDAD = 11;
  public static final int SGAPOSICIONUBICACIONVIEW = 12;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavubicacionlibresloViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtipmac
   */
  public String getIdtipmac()
  {
    return (String)getAttributeInternal(IDTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtipmac
   */
  public void setIdtipmac(String value)
  {
    setAttributeInternal(IDTIPMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idubi
   */
  public String getIdubi()
  {
    return (String)getAttributeInternal(IDUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idubi
   */
  public void setIdubi(String value)
  {
    setAttributeInternal(IDUBI, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Posicion
   */
  public Number getPosicion()
  {
    return (Number)getAttributeInternal(POSICION);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Posicion
   */
  public void setPosicion(Number value)
  {
    setAttributeInternal(POSICION, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Udistancia
   */
  public Number getUdistancia()
  {
    return (Number)getAttributeInternal(UDISTANCIA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Udistancia
   */
  public void setUdistancia(Number value)
  {
    setAttributeInternal(UDISTANCIA, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtipubi
   */
  public String getIdtipubi()
  {
    return (String)getAttributeInternal(IDTIPUBI);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtipubi
   */
  public void setIdtipubi(String value)
  {
    setAttributeInternal(IDTIPUBI, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Pasillo
   */
  public Number getPasillo()
  {
    return (Number)getAttributeInternal(PASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Pasillo
   */
  public void setPasillo(Number value)
  {
    setAttributeInternal(PASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Columna
   */
  public Number getColumna()
  {
    return (Number)getAttributeInternal(COLUMNA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Columna
   */
  public void setColumna(Number value)
  {
    setAttributeInternal(COLUMNA, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Nivel
   */
  public Number getNivel()
  {
    return (Number)getAttributeInternal(NIVEL);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Nivel
   */
  public void setNivel(Number value)
  {
    setAttributeInternal(NIVEL, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Lado
   */
  public String getLado()
  {
    return (String)getAttributeInternal(LADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Lado
   */
  public void setLado(String value)
  {
    setAttributeInternal(LADO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Rotacion
   */
  public String getRotacion()
  {
    return (String)getAttributeInternal(ROTACION);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Rotacion
   */
  public void setRotacion(String value)
  {
    setAttributeInternal(ROTACION, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Numpos
   */
  public Number getNumpos()
  {
    return (Number)getAttributeInternal(NUMPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Numpos
   */
  public void setNumpos(Number value)
  {
    setAttributeInternal(NUMPOS, value);
  }


  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTIPMAC:
        return getIdtipmac();
      case IDUBI:
        return getIdubi();
      case POSICION:
        return getPosicion();
      case UDISTANCIA:
        return getUdistancia();
      case IDTIPUBI:
        return getIdtipubi();
      case PASILLO:
        return getPasillo();
      case COLUMNA:
        return getColumna();
      case NIVEL:
        return getNivel();
      case LADO:
        return getLado();
      case ROTACION:
        return getRotacion();
      case NUMPOS:
        return getNumpos();
      case PRIORIDAD:
        return getPrioridad();
      case SGAPOSICIONUBICACIONVIEW:
        return getSgaposicionubicacionView();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDTIPMAC:
        setIdtipmac((String)value);
        return;
      case IDUBI:
        setIdubi((String)value);
        return;
      case POSICION:
        setPosicion((Number)value);
        return;
      case UDISTANCIA:
        setUdistancia((Number)value);
        return;
      case IDTIPUBI:
        setIdtipubi((String)value);
        return;
      case PASILLO:
        setPasillo((Number)value);
        return;
      case COLUMNA:
        setColumna((Number)value);
        return;
      case NIVEL:
        setNivel((Number)value);
        return;
      case LADO:
        setLado((String)value);
        return;
      case ROTACION:
        setRotacion((String)value);
        return;
      case NUMPOS:
        setNumpos((Number)value);
        return;
      case PRIORIDAD:
        setPrioridad((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the associated <code>Row</code> using master-detail link SgaposicionubicacionView
   */
  public oracle.jbo.Row getSgaposicionubicacionView()
  {
    return (oracle.jbo.Row)getAttributeInternal(SGAPOSICIONUBICACIONVIEW);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Prioridad
   */
  public Number getPrioridad()
  {
    return (Number)getAttributeInternal(PRIORIDAD);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Prioridad
   */
  public void setPrioridad(Number value)
  {
    setAttributeInternal(PRIORIDAD, value);
  }
}