package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavordtranpendtrasloextraViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavordtranpendtrasloextraViewRow 
{


  public static final int IDORD = 0;
  public static final int IDTIP = 1;
  public static final int ESTADO = 2;
  public static final int IDMAC = 3;
  public static final int IDORDREUBIC = 4;
  public static final int CREATEDBY = 5;
  public static final int CREATEDON = 6;
  public static final int MODIFIEDBY = 7;
  public static final int MODIFIEDON = 8;
  public static final int CODERROR = 9;
  public static final int IDTRASLO = 10;
  public static final int IDTIPMAC = 11;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavordtranpendtrasloextraViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idord
   */
  public Number getIdord()
  {
    return (Number)getAttributeInternal(IDORD);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idord
   */
  public void setIdord(Number value)
  {
    setAttributeInternal(IDORD, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtip
   */
  public String getIdtip()
  {
    return (String)getAttributeInternal(IDTIP);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtip
   */
  public void setIdtip(String value)
  {
    setAttributeInternal(IDTIP, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idordreubic
   */
  public Number getIdordreubic()
  {
    return (Number)getAttributeInternal(IDORDREUBIC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idordreubic
   */
  public void setIdordreubic(Number value)
  {
    setAttributeInternal(IDORDREUBIC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Createdby
   */
  public void setCreatedby(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Createdon
   */
  public Date getCreatedon()
  {
    return (Date)getAttributeInternal(CREATEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Createdon
   */
  public void setCreatedon(Date value)
  {
    setAttributeInternal(CREATEDON, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Modifiedby
   */
  public String getModifiedby()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Modifiedby
   */
  public void setModifiedby(String value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Modifiedon
   */
  public Date getModifiedon()
  {
    return (Date)getAttributeInternal(MODIFIEDON);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Modifiedon
   */
  public void setModifiedon(Date value)
  {
    setAttributeInternal(MODIFIEDON, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Coderror
   */
  public Number getCoderror()
  {
    return (Number)getAttributeInternal(CODERROR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Coderror
   */
  public void setCoderror(Number value)
  {
    setAttributeInternal(CODERROR, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtraslo
   */
  public Number getIdtraslo()
  {
    return (Number)getAttributeInternal(IDTRASLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtraslo
   */
  public void setIdtraslo(Number value)
  {
    setAttributeInternal(IDTRASLO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        return getIdord();
      case IDTIP:
        return getIdtip();
      case ESTADO:
        return getEstado();
      case IDMAC:
        return getIdmac();
      case IDORDREUBIC:
        return getIdordreubic();
      case CREATEDBY:
        return getCreatedby();
      case CREATEDON:
        return getCreatedon();
      case MODIFIEDBY:
        return getModifiedby();
      case MODIFIEDON:
        return getModifiedon();
      case CODERROR:
        return getCoderror();
      case IDTRASLO:
        return getIdtraslo();
      case IDTIPMAC:
        return getIdtipmac();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDORD:
        setIdord((Number)value);
        return;
      case IDTIP:
        setIdtip((String)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      case IDMAC:
        setIdmac((String)value);
        return;
      case IDORDREUBIC:
        setIdordreubic((Number)value);
        return;
      case CREATEDBY:
        setCreatedby((String)value);
        return;
      case CREATEDON:
        setCreatedon((Date)value);
        return;
      case MODIFIEDBY:
        setModifiedby((String)value);
        return;
      case MODIFIEDON:
        setModifiedon((Date)value);
        return;
      case CODERROR:
        setCoderror((Number)value);
        return;
      case IDTRASLO:
        setIdtraslo((Number)value);
        return;
      case IDTIPMAC:
        setIdtipmac((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtipmac
   */
  public String getIdtipmac()
  {
    return (String)getAttributeInternal(IDTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtipmac
   */
  public void setIdtipmac(String value)
  {
    setAttributeInternal(IDTIPMAC, value);
  }
}