package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavpasillosintrasloViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavpasillosintrasloViewRow 
{


  public static final int IDPASILLO = 0;
  public static final int ESTADO = 1;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavpasillosintrasloViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idpasillo
   */
  public Number getIdpasillo()
  {
    return (Number)getAttributeInternal(IDPASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idpasillo
   */
  public void setIdpasillo(Number value)
  {
    setAttributeInternal(IDPASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDPASILLO:
        return getIdpasillo();
      case ESTADO:
        return getEstado();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDPASILLO:
        setIdpasillo((Number)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
  
  public boolean isDisponiblePasillo()
  {
    return getEstado().equals("1");
  }
}