package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavpasillocandidateViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavpasillocandidateViewRow 
{


  public static final int IDPASILLO = 0;
  public static final int PRIORIDAD = 1;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavpasillocandidateViewRowImpl()
  {
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDPASILLO:
        return getIdpasillo();
      case PRIORIDAD:
        return getPrioridad();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDPASILLO:
        setIdpasillo((Number)value);
        return;
      case PRIORIDAD:
        setPrioridad((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idpasillo
   */
  public Number getIdpasillo()
  {
    return (Number)getAttributeInternal(IDPASILLO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idpasillo
   */
  public void setIdpasillo(Number value)
  {
    setAttributeInternal(IDPASILLO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Prioridad
   */
  public Number getPrioridad()
  {
    return (Number)getAttributeInternal(PRIORIDAD);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Prioridad
   */
  public void setPrioridad(Number value)
  {
    setAttributeInternal(PRIORIDAD, value);
  }
}