package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavmacViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.dmc.common.SgavmacViewRow 
{


  public static final int IDMAC = 0;
  public static final int MULTIREF = 1;
  public static final int IDTIPMAC = 2;
  public static final int ESTADO = 3;
  public static final int UBIPOS = 4;
  public static final int DESCVISUALPOS = 5;
  public static final int POSUBIPOS = 6;
  public static final int UBIDES = 7;
  public static final int DESCVISUALDES = 8;
  public static final int POSUBIDES = 9;
  public static final int SGAVEXISTENCIAVIEW = 10;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavmacViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Multiref
   */
  public String getMultiref()
  {
    return (String)getAttributeInternal(MULTIREF);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Multiref
   */
  public void setMultiref(String value)
  {
    setAttributeInternal(MULTIREF, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtipmac
   */
  public String getIdtipmac()
  {
    return (String)getAttributeInternal(IDTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtipmac
   */
  public void setIdtipmac(String value)
  {
    setAttributeInternal(IDTIPMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Ubipos
   */
  public String getUbipos()
  {
    return (String)getAttributeInternal(UBIPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Ubipos
   */
  public void setUbipos(String value)
  {
    setAttributeInternal(UBIPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Descvisualpos
   */
  public String getDescvisualpos()
  {
    return (String)getAttributeInternal(DESCVISUALPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Descvisualpos
   */
  public void setDescvisualpos(String value)
  {
    setAttributeInternal(DESCVISUALPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Posubipos
   */
  public Number getPosubipos()
  {
    return (Number)getAttributeInternal(POSUBIPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Posubipos
   */
  public void setPosubipos(Number value)
  {
    setAttributeInternal(POSUBIPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Ubides
   */
  public String getUbides()
  {
    return (String)getAttributeInternal(UBIDES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Ubides
   */
  public void setUbides(String value)
  {
    setAttributeInternal(UBIDES, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Descvisualdes
   */
  public String getDescvisualdes()
  {
    return (String)getAttributeInternal(DESCVISUALDES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Descvisualdes
   */
  public void setDescvisualdes(String value)
  {
    setAttributeInternal(DESCVISUALDES, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Posubides
   */
  public Number getPosubides()
  {
    return (Number)getAttributeInternal(POSUBIDES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Posubides
   */
  public void setPosubides(Number value)
  {
    setAttributeInternal(POSUBIDES, value);
  }

  /**
   * 
   *  Gets the associated <code>RowIterator</code> using master-detail link SgavexistenciaView
   */
  public oracle.jbo.RowIterator getSgavexistenciaView()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(SGAVEXISTENCIAVIEW);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        return getIdmac();
      case MULTIREF:
        return getMultiref();
      case IDTIPMAC:
        return getIdtipmac();
      case ESTADO:
        return getEstado();
      case UBIPOS:
        return getUbipos();
      case DESCVISUALPOS:
        return getDescvisualpos();
      case POSUBIPOS:
        return getPosubipos();
      case UBIDES:
        return getUbides();
      case DESCVISUALDES:
        return getDescvisualdes();
      case POSUBIDES:
        return getPosubides();
      case SGAVEXISTENCIAVIEW:
        return getSgavexistenciaView();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDMAC:
        setIdmac((String)value);
        return;
      case MULTIREF:
        setMultiref((String)value);
        return;
      case IDTIPMAC:
        setIdtipmac((String)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      case UBIPOS:
        setUbipos((String)value);
        return;
      case DESCVISUALPOS:
        setDescvisualpos((String)value);
        return;
      case POSUBIPOS:
        setPosubipos((Number)value);
        return;
      case UBIDES:
        setUbides((String)value);
        return;
      case DESCVISUALDES:
        setDescvisualdes((String)value);
        return;
      case POSUBIDES:
        setPosubides((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}