package es.sysmap.interflex.model.dmc;
import es.sysmap.interflex.model.dmc.SgavldocunicalineaViewImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavldocunicalineaViewRowImpl extends ViewRowImpl 
{


  public static final int IDDOC = 0;
  public static final int IDLIN = 1;
  public static final int CANPEN = 2;
  public static final int MOTIVO = 3;
  public static final int CANTOT = 4;
  public static final int ESTADO = 5;
  public static final int PESO = 6;
  public static final int CANRES = 7;
  public static final int IDART = 8;
  public static final int IDPUESTO = 9;
  public static final int SGALDOCVIEW = 10;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavldocunicalineaViewRowImpl()
  {
  }

  public void activarLinia (String idPuesto)
  {
    SgaldocViewRowImpl row = (SgaldocViewRowImpl)getSgaldocView();
    row.activar(idPuesto, true, true);  // Sin mirar otras líneas
  }

  
  /**
   * @see es.sysmap.interflex.model.dmc.SgavldocunicalineaViewImpl#asignarDocsUnicaLineaMismoArticulo
   * @return 
   */
  public int asignarDocsUnicaLineaMismoArticulo(String idPuesto)
  {
    SgavldocunicalineaViewImpl vo = (SgavldocunicalineaViewImpl)getViewObject();
    return vo.asignarDocsUnicaLineaMismoArticulo(idPuesto, getIddoc(), getIdart());
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Iddoc
   */
  public Number getIddoc()
  {
    return (Number)getAttributeInternal(IDDOC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Iddoc
   */
  public void setIddoc(Number value)
  {
    setAttributeInternal(IDDOC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idlin
   */
  public Number getIdlin()
  {
    return (Number)getAttributeInternal(IDLIN);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idlin
   */
  public void setIdlin(Number value)
  {
    setAttributeInternal(IDLIN, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Canpen
   */
  public Number getCanpen()
  {
    return (Number)getAttributeInternal(CANPEN);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Canpen
   */
  public void setCanpen(Number value)
  {
    setAttributeInternal(CANPEN, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Motivo
   */
  public String getMotivo()
  {
    return (String)getAttributeInternal(MOTIVO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Motivo
   */
  public void setMotivo(String value)
  {
    setAttributeInternal(MOTIVO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Cantot
   */
  public Number getCantot()
  {
    return (Number)getAttributeInternal(CANTOT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Cantot
   */
  public void setCantot(Number value)
  {
    setAttributeInternal(CANTOT, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Estado
   */
  public String getEstado()
  {
    return (String)getAttributeInternal(ESTADO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Estado
   */
  public void setEstado(String value)
  {
    setAttributeInternal(ESTADO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Peso
   */
  public Number getPeso()
  {
    return (Number)getAttributeInternal(PESO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Peso
   */
  public void setPeso(Number value)
  {
    setAttributeInternal(PESO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Canres
   */
  public Number getCanres()
  {
    return (Number)getAttributeInternal(CANRES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Canres
   */
  public void setCanres(Number value)
  {
    setAttributeInternal(CANRES, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idart
   */
  public String getIdart()
  {
    return (String)getAttributeInternal(IDART);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idart
   */
  public void setIdart(String value)
  {
    setAttributeInternal(IDART, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idpuesto
   */
  public String getIdpuesto()
  {
    return (String)getAttributeInternal(IDPUESTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idpuesto
   */
  public void setIdpuesto(String value)
  {
    setAttributeInternal(IDPUESTO, value);
  }


  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOC:
        return getIddoc();
      case IDLIN:
        return getIdlin();
      case CANPEN:
        return getCanpen();
      case MOTIVO:
        return getMotivo();
      case CANTOT:
        return getCantot();
      case ESTADO:
        return getEstado();
      case PESO:
        return getPeso();
      case CANRES:
        return getCanres();
      case IDART:
        return getIdart();
      case IDPUESTO:
        return getIdpuesto();
      case SGALDOCVIEW:
        return getSgaldocView();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOC:
        setIddoc((Number)value);
        return;
      case IDLIN:
        setIdlin((Number)value);
        return;
      case CANPEN:
        setCanpen((Number)value);
        return;
      case MOTIVO:
        setMotivo((String)value);
        return;
      case CANTOT:
        setCantot((Number)value);
        return;
      case ESTADO:
        setEstado((String)value);
        return;
      case PESO:
        setPeso((Number)value);
        return;
      case CANRES:
        setCanres((Number)value);
        return;
      case IDART:
        setIdart((String)value);
        return;
      case IDPUESTO:
        setIdpuesto((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the associated <code>Row</code> using master-detail link SgaldocView
   */
  public oracle.jbo.Row getSgaldocView()
  {
    return (oracle.jbo.Row)getAttributeInternal(SGALDOCVIEW);
  }







}