package es.sysmap.interflex.model.dmc;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavbultoDispSortidaViewImpl extends ViewObjectImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavbultoDispSortidaViewImpl()
  {
  }
}