package es.sysmap.interflex.model.tst.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface SgavdisponibleentradaViewRow extends Row 
{
  String getIdart();

  oracle.jbo.domain.Number getIdbulto();

  oracle.jbo.domain.Number getIddoc();

  oracle.jbo.domain.Number getIdlin();

  String getIdmac();

  oracle.jbo.domain.Number getCanres();

  oracle.jbo.domain.Number getCantot();
}