package es.sysmap.interflex.modelrpsprod.dmc.common;
import oracle.jbo.ApplicationModule;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface AppModule extends ApplicationModule 
{
  void updateEmbalajes();

  void updateEmbalajesReferencia();
}