package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgadifstockhostRowClient extends RowImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgadifstockhostRowClient()
  {
  }

  public oracle.jbo.domain.Number getCantot()
  {
    return (oracle.jbo.domain.Number)getAttribute("Cantot");
  }

  public String getIdart()
  {
    return (String)getAttribute("Idart");
  }

  public String getIdartif()
  {
    return (String)getAttribute("Idartif");
  }






}