package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaldocViewRowClient extends RowImpl implements es.sysmap.interflex.model.dmc.common.SgaldocViewRow  
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaldocViewRowClient()
  {
  }










































































































































































































































































































































































































































































































































  public void actualitzarLinia(String estat, String puesto)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "actualitzarLinia", new String[] {"java.lang.String", "java.lang.String"}, new Object[] {estat, puesto});
    return;
  }

  public void reservarSalida(String idmac, oracle.jbo.domain.Number canres)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "reservarSalida", new String[] {"java.lang.String", "oracle.jbo.domain.Number"}, new Object[] {idmac, canres});
    return;
  }

  public String getEstadoCabecera()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getEstadoCabecera", null, null);
    return (String)_ret;
  }

  public oracle.jbo.RowIterator getSgalbultoView()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getSgalbultoView", null, null);
    return (oracle.jbo.RowIterator)_ret;
  }

  public void activarLinia(String idPuesto, boolean mld, boolean slo)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "activarLinia", new String[] {"java.lang.String", "boolean", "boolean"}, new Object[] {idPuesto, new Boolean(mld), new Boolean(slo)});
    return;
  }

  public String getNalbaran()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getNalbaran", null, null);
    return (String)_ret;
  }

  public String getIdcabnum()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getIdcabnum", null, null);
    return (String)_ret;
  }

  public String getEstado()
  {
    return (String)getAttribute("Estado");
  }

  public String getIdpuesto()
  {
    return (String)getAttribute("Idpuesto");
  }

  public String getIdart()
  {
    return (String)getAttribute("Idart");
  }

  public oracle.jbo.domain.Number getIdlin()
  {
    return (oracle.jbo.domain.Number)getAttribute("Idlin");
  }

  public void setEstado(String value)
  {
    setAttribute("Estado", value);
  }

  public String getIdartif()
  {
    return (String)getAttribute("Idartif");
  }

  public String getModifiedby()
  {
    return (String)getAttribute("Modifiedby");
  }

  public oracle.jbo.domain.Number getIddoc()
  {
    return (oracle.jbo.domain.Number)getAttribute("Iddoc");
  }

  public String getSinformato()
  {
    return (String)getAttribute("Sinformato");
  }

  public void setSinformato(String value)
  {
    setAttribute("Sinformato", value);
  }







}