package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaresmatViewRowClient extends RowImpl  
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaresmatViewRowClient()
  {
  }

  public oracle.jbo.domain.Number getIddoc()
  {
    return (oracle.jbo.domain.Number)getAttribute("Iddoc");
  }

  public void setIddoc(oracle.jbo.domain.Number value)
  {
    setAttribute("Iddoc", value);
  }

  public oracle.jbo.domain.Number getIdlin()
  {
    return (oracle.jbo.domain.Number)getAttribute("Idlin");
  }

  public void setIdlin(oracle.jbo.domain.Number value)
  {
    setAttribute("Idlin", value);
  }

  public String getIdmac()
  {
    return (String)getAttribute("Idmac");
  }

  public void setIdmac(String value)
  {
    setAttribute("Idmac", value);
  }

  public oracle.jbo.domain.Number getCanres()
  {
    return (oracle.jbo.domain.Number)getAttribute("Canres");
  }

  public void setCanres(oracle.jbo.domain.Number value)
  {
    setAttribute("Canres", value);
  }

  public oracle.jbo.domain.Number getIdbulto()
  {
    return (oracle.jbo.domain.Number)getAttribute("Idbulto");
  }

  public void setIdbulto(oracle.jbo.domain.Number value)
  {
    setAttribute("Idbulto", value);
  }

  public String getIdart()
  {
    return (String)getAttribute("Idart");
  }

  public void setIdart(String value)
  {
    setAttribute("Idart", value);
  }



















































































































































































































































































}