package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgatipoubicacionViewRowClient extends RowImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgatipoubicacionViewRowClient()
  {
  }

  public String getIdtipubi()
  {
    return (String)getAttribute("Idtipubi");
  }

  public void setIdtipubi(String value)
  {
    setAttribute("Idtipubi", value);
  }

  public String getDescrip()
  {
    return (String)getAttribute("Descrip");
  }

  public void setDescrip(String value)
  {
    setAttribute("Descrip", value);
  }

































}