package es.sysmap.interflex.model.dmc.client;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionSiloViewRowClient extends SgaubicacionViewRowClient 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionSiloViewRowClient()
  {
  }

  public String getIdtipalm()
  {
    return (String)getAttribute("Idtipalm");
  }

  public void setIdtipalm(String value)
  {
    setAttribute("Idtipalm", value);
  }

  public String getIdubi()
  {
    return (String)getAttribute("Idubi");
  }

  public void setIdubi(String value)
  {
    setAttribute("Idubi", value);
  }

  public String getIdtipubi()
  {
    return (String)getAttribute("Idtipubi");
  }

  public void setIdtipubi(String value)
  {
    setAttribute("Idtipubi", value);
  }

  public String getDescrip()
  {
    return (String)getAttribute("Descrip");
  }

  public void setDescrip(String value)
  {
    setAttribute("Descrip", value);
  }

  public oracle.jbo.domain.Number getPasillo()
  {
    return (oracle.jbo.domain.Number)getAttribute("Pasillo");
  }

  public void setPasillo(oracle.jbo.domain.Number value)
  {
    setAttribute("Pasillo", value);
  }

  public oracle.jbo.domain.Number getColumna()
  {
    return (oracle.jbo.domain.Number)getAttribute("Columna");
  }

  public void setColumna(oracle.jbo.domain.Number value)
  {
    setAttribute("Columna", value);
  }

  public oracle.jbo.domain.Number getNivel()
  {
    return (oracle.jbo.domain.Number)getAttribute("Nivel");
  }

  public void setNivel(oracle.jbo.domain.Number value)
  {
    setAttribute("Nivel", value);
  }

  public String getLado()
  {
    return (String)getAttribute("Lado");
  }

  public void setLado(String value)
  {
    setAttribute("Lado", value);
  }

  public String getRotacion()
  {
    return (String)getAttribute("Rotacion");
  }

  public void setRotacion(String value)
  {
    setAttribute("Rotacion", value);
  }

















































































































































}