package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.ViewUsageImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionPlcViewClient extends ViewUsageImpl implements es.sysmap.interflex.model.dmc.common.SgaubicacionPlcView 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionPlcViewClient()
  {
  }

  public String getUbicacion44()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getUbicacion44", null, null);
    return (String)_ret;
  }

  public String getUbicacion6()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getUbicacion6", null, null);
    return (String)_ret;
  }

  public es.sysmap.interflex.model.dmc.common.SgaubicacionPlcViewRow getUbicacionEntradaMLD()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getUbicacionEntradaMLD", null, null);
    return (es.sysmap.interflex.model.dmc.common.SgaubicacionPlcViewRow)_ret;
  }






























}