package es.sysmap.interflex.model.dmc.client;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgaubicacionPlcViewRowClient extends SgaubicacionViewRowClient implements es.sysmap.interflex.model.dmc.common.SgaubicacionPlcViewRow 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgaubicacionPlcViewRowClient()
  {
  }








































































  public String getDescripvisual()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getDescripvisual", null, null);
    return (String)_ret;
  }

  public oracle.jbo.domain.Number getCappul()
  {
    return (oracle.jbo.domain.Number)getAttribute("Cappul");
  }

  public String getDescrip()
  {
    return (String)getAttribute("Descrip");
  }

  public String getIdtipalm()
  {
    return (String)getAttribute("Idtipalm");
  }

  public String getIdtipubi()
  {
    return (String)getAttribute("Idtipubi");
  }

  public String getIdubi()
  {
    return (String)getAttribute("Idubi");
  }

  public oracle.jbo.domain.Number getPosplc()
  {
    return (oracle.jbo.domain.Number)getAttribute("Posplc");
  }

  public void setCappul(oracle.jbo.domain.Number value)
  {
    setAttribute("Cappul", value);
  }

  public void setDescrip(String value)
  {
    setAttribute("Descrip", value);
  }

  public void setIdtipalm(String value)
  {
    setAttribute("Idtipalm", value);
  }

  public void setIdtipubi(String value)
  {
    setAttribute("Idtipubi", value);
  }

  public void setIdubi(String value)
  {
    setAttribute("Idubi", value);
  }
















































































































































}