package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavordtranpasillotrasloViewRowClient extends RowImpl implements es.sysmap.interflex.model.dmc.common.SgavordtranpasillotrasloViewRow 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavordtranpasillotrasloViewRowClient()
  {
  }




















































































  public void asignarOrdenTraslo(int idTraslo)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "asignarOrdenTraslo", new String[] {"int"}, new Object[] {new Integer(idTraslo)});
    return;
  }

  public boolean isOrdenReubicacion()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "isOrdenReubicacion", null, null);
    return ((Boolean)_ret).booleanValue();
  }

  public String getIdmac()
  {
    return (String)getAttribute("Idmac");
  }

  public oracle.jbo.domain.Number getIdord()
  {
    return (oracle.jbo.domain.Number)getAttribute("Idord");
  }

  public void setSeqmld(oracle.jbo.domain.Number value)
  {
    setAttribute("Seqmld", value);
  }








}