package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavldocEntradesViewRowClient extends RowImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavldocEntradesViewRowClient()
  {
  }

  public oracle.jbo.domain.Number getIddoc()
  {
    return (oracle.jbo.domain.Number)getAttribute("Iddoc");
  }


}