package es.sysmap.interflex.model.dmc.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavarticulomodpesViewRowClient extends RowImpl implements es.sysmap.interflex.model.dmc.common.SgavarticulomodpesViewRow  
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavarticulomodpesViewRowClient()
  {
  }
















  public String isOkSetPesUnitari()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "isOkSetPesUnitari", null, null);
    return (String)_ret;
  }

  public void setPesActual(oracle.jbo.domain.Number value)
  {
    setAttribute("PesActual", value);
  }

  public void setPesunit(oracle.jbo.domain.Number value)
  {
    setAttribute("Pesunit", value);
  }

  public oracle.jbo.domain.Number getPesUnitariReal()
  {
    return (oracle.jbo.domain.Number)getAttribute("PesUnitariReal");
  }



























}