package es.sysmap.interflex.modelrpsprod.dmc;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class EmbalajesreferenciaViewRowImpl extends ViewRowImpl 
{


  public static final int CODART = 0;
  public static final int IDFORMATO = 1;
  public static final int CANTIDAD = 2;
  public static final int PREDET = 3;
  public static final int UNIDADMEDIDA = 4;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public EmbalajesreferenciaViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Codart
   */
  public String getCodart()
  {
    return (String)getAttributeInternal(CODART);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Codart
   */
  public void setCodart(String value)
  {
    setAttributeInternal(CODART, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idformato
   */
  public Integer getIdformato()
  {
    return (Integer)getAttributeInternal(IDFORMATO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idformato
   */
  public void setIdformato(Integer value)
  {
    setAttributeInternal(IDFORMATO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Cantidad
   */
  public Integer getCantidad()
  {
    return (Integer)getAttributeInternal(CANTIDAD);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Cantidad
   */
  public void setCantidad(Integer value)
  {
    setAttributeInternal(CANTIDAD, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Predet
   */
  public Boolean getPredet()
  {
    return (Boolean)getAttributeInternal(PREDET);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Predet
   */
  public void setPredet(Boolean value)
  {
    setAttributeInternal(PREDET, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Unidadmedida
   */
  public String getUnidadmedida()
  {
    return (String)getAttributeInternal(UNIDADMEDIDA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Unidadmedida
   */
  public void setUnidadmedida(String value)
  {
    setAttributeInternal(UNIDADMEDIDA, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CODART:
        return getCodart();
      case IDFORMATO:
        return getIdformato();
      case CANTIDAD:
        return getCantidad();
      case PREDET:
        return getPredet();
      case UNIDADMEDIDA:
        return getUnidadmedida();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}