package es.sysmap.interflex.model.tst;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class SgavdisponibleentradaViewRowImpl extends ViewRowImpl implements es.sysmap.interflex.model.tst.common.SgavdisponibleentradaViewRow 
{


  public static final int IDDOC = 0;
  public static final int IDLIN = 1;
  public static final int IDBULTO = 2;
  public static final int IDMAC = 3;
  public static final int IDART = 4;
  public static final int CANTOT = 5;
  public static final int CANRES = 6;
  public static final int UNIMAC = 7;
  public static final int UBIPOS = 8;
  public static final int POSUBIPOS = 9;
  public static final int IDTIPMAC = 10;
  public static final int IDPUESTO = 11;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public SgavdisponibleentradaViewRowImpl()
  {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Iddoc
   */
  public Number getIddoc()
  {
    return (Number)getAttributeInternal(IDDOC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Iddoc
   */
  public void setIddoc(Number value)
  {
    setAttributeInternal(IDDOC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idlin
   */
  public Number getIdlin()
  {
    return (Number)getAttributeInternal(IDLIN);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idlin
   */
  public void setIdlin(Number value)
  {
    setAttributeInternal(IDLIN, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idbulto
   */
  public Number getIdbulto()
  {
    return (Number)getAttributeInternal(IDBULTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idbulto
   */
  public void setIdbulto(Number value)
  {
    setAttributeInternal(IDBULTO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idmac
   */
  public String getIdmac()
  {
    return (String)getAttributeInternal(IDMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idmac
   */
  public void setIdmac(String value)
  {
    setAttributeInternal(IDMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idart
   */
  public String getIdart()
  {
    return (String)getAttributeInternal(IDART);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idart
   */
  public void setIdart(String value)
  {
    setAttributeInternal(IDART, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Cantot
   */
  public Number getCantot()
  {
    return (Number)getAttributeInternal(CANTOT);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Cantot
   */
  public void setCantot(Number value)
  {
    setAttributeInternal(CANTOT, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Canres
   */
  public Number getCanres()
  {
    return (Number)getAttributeInternal(CANRES);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Canres
   */
  public void setCanres(Number value)
  {
    setAttributeInternal(CANRES, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Unimac
   */
  public Number getUnimac()
  {
    return (Number)getAttributeInternal(UNIMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Unimac
   */
  public void setUnimac(Number value)
  {
    setAttributeInternal(UNIMAC, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Ubipos
   */
  public String getUbipos()
  {
    return (String)getAttributeInternal(UBIPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Ubipos
   */
  public void setUbipos(String value)
  {
    setAttributeInternal(UBIPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Posubipos
   */
  public Number getPosubipos()
  {
    return (Number)getAttributeInternal(POSUBIPOS);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Posubipos
   */
  public void setPosubipos(Number value)
  {
    setAttributeInternal(POSUBIPOS, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idtipmac
   */
  public String getIdtipmac()
  {
    return (String)getAttributeInternal(IDTIPMAC);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idtipmac
   */
  public void setIdtipmac(String value)
  {
    setAttributeInternal(IDTIPMAC, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOC:
        return getIddoc();
      case IDLIN:
        return getIdlin();
      case IDBULTO:
        return getIdbulto();
      case IDMAC:
        return getIdmac();
      case IDART:
        return getIdart();
      case CANTOT:
        return getCantot();
      case CANRES:
        return getCanres();
      case UNIMAC:
        return getUnimac();
      case UBIPOS:
        return getUbipos();
      case POSUBIPOS:
        return getPosubipos();
      case IDTIPMAC:
        return getIdtipmac();
      case IDPUESTO:
        return getIdpuesto();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOC:
        setIddoc((Number)value);
        return;
      case IDLIN:
        setIdlin((Number)value);
        return;
      case IDBULTO:
        setIdbulto((Number)value);
        return;
      case IDMAC:
        setIdmac((String)value);
        return;
      case IDART:
        setIdart((String)value);
        return;
      case CANTOT:
        setCantot((Number)value);
        return;
      case CANRES:
        setCanres((Number)value);
        return;
      case UNIMAC:
        setUnimac((Number)value);
        return;
      case UBIPOS:
        setUbipos((String)value);
        return;
      case POSUBIPOS:
        setPosubipos((Number)value);
        return;
      case IDTIPMAC:
        setIdtipmac((String)value);
        return;
      case IDPUESTO:
        setIdpuesto((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Idpuesto
   */
  public String getIdpuesto()
  {
    return (String)getAttributeInternal(IDPUESTO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Idpuesto
   */
  public void setIdpuesto(String value)
  {
    setAttributeInternal(IDPUESTO, value);
  }
  
}