package es.sysmap.interflex.erps_model.bdc;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.Key;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class ZAgenciatipoenvioImpl extends EntityImpl 
{
  public static final int ID = 0;
  public static final int CODTRA = 1;
  public static final int TIPOENVIO = 2;
  public static final int ZTIPOENVIO = 3;






  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public ZAgenciatipoenvioImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("es.sysmap.interflex.erps_model.bdc.ZAgenciatipoenvio");
    }
    return mDefinitionObject;
  }







  /**
   * 
   *  Gets the attribute value for Id, using the alias name Id
   */
  public Integer getId()
  {
    return (Integer)getAttributeInternal(ID);
  }

  /**
   * 
   *  Gets the attribute value for Codtra, using the alias name Codtra
   */
  public String getCodtra()
  {
    return (String)getAttributeInternal(CODTRA);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Codtra
   */
  public void setCodtra(String value)
  {
    setAttributeInternal(CODTRA, value);
  }

  /**
   * 
   *  Gets the attribute value for Tipoenvio, using the alias name Tipoenvio
   */
  public String getTipoenvio()
  {
    return (String)getAttributeInternal(TIPOENVIO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Tipoenvio
   */
  public void setTipoenvio(String value)
  {
    setAttributeInternal(TIPOENVIO, value);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case CODTRA:
        return getCodtra();
      case TIPOENVIO:
        return getTipoenvio();
      case ZTIPOENVIO:
        return getZTipoenvio();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CODTRA:
        setCodtra((String)value);
        return;
      case TIPOENVIO:
        setTipoenvio((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   *  Gets the associated entity ZTipoenvioImpl
   */
  public ZTipoenvioImpl getZTipoenvio()
  {
    return (ZTipoenvioImpl)getAttributeInternal(ZTIPOENVIO);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity ZTipoenvioImpl
   */
  public void setZTipoenvio(ZTipoenvioImpl value)
  {
    setAttributeInternal(ZTIPOENVIO, value);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Integer id)
  {
    return new Key(new Object[] {id});
  }






}